/*
 http://creativecommons.org/licenses/by/2.5/
 - Free for use in both personal and commercial projects
 - Attribution requires leaving author name, author link, and the license info intact

 Modified by Jubal Slone and Max Morgan for lifetechnologies.com

*/
!function($){var LightboxOptions=function(){function LightboxOptions(){this.fadeDuration=500;this.fitImagesInViewport=true;this.resizeDuration=700;this.positionFromTop=50;this.showImageNumberLabel=true;this.alwaysShowNavOnTouchDevices=true;this.wrapAround=true;this.showThumbnails=true}LightboxOptions.prototype.albumLabel=function(curImageNum,albumSize){return"Image "+curImageNum+" of "+albumSize};return LightboxOptions}();var Lightbox=function(){function Lightbox(options){this.options=options;this.album=
[];this.currentImageIndex=void 0;this.built=false;this.init()}Lightbox.prototype.init=function(){this.enable()};Lightbox.prototype.enable=function(){var self=this;$("body").on("click","a[rel^\x3dlightbox], area[rel^\x3dlightbox], a[data-lightbox], area[data-lightbox]",function(event){self.start($(event.currentTarget));return false})};Lightbox.prototype.build=function(){if(this.built)return;this.built=true;var self=this;var $lightboxOverlay=$("\x3cdiv id\x3d'lightboxOverlay' class\x3d'lightboxOverlay'\x3e\x3c/div\x3e");
var $lightbox=$("\x3cdiv id\x3d'lightbox' class\x3d'lightbox'\x3e\x3c/div\x3e");var $lb_outerContainer=$("\x3cdiv class\x3d'lb-outerContainer'\x3e \x3cdiv class\x3d'lb-container'\x3e \x3cdiv class\x3d'lb-closeContainer'\x3e\x3ca class\x3d'lb-close'\x3e\x26times;\x3c/a\x3e\x3c/div\x3e\x3cimg class\x3d'lb-image' src\x3d''/\x3e \x3cdiv class\x3d'lb-nav'\x3e\x3cspan class\x3d'lb-prev'\x3e\x3c/span\x3e\x3cspan class\x3d'lb-next'\x3e\x3c/span\x3e\x3c/div\x3e\x3cdiv class\x3d'lb-loader'\x3e\x3cspan class\x3d'loading-wheel loading-wheel-lg'\x3e\x3c/span\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");
var $lb_dataContainer=$("\x3cdiv class\x3d'lb-dataContainer'\x3e \x3cdiv class\x3d'lb-headline'\x3e\x3c/div\x3e\x3cdiv class\x3d'lb-data'\x3e \x3cdiv class\x3d'lb-details'\x3e\x3cspan class\x3d'lb-caption'\x3e\x3c/span\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");$lightbox.append($lb_outerContainer,$lb_dataContainer);$("body").append($lightboxOverlay,$lightbox);this.$lightbox=$("#lightbox");this.$overlay=$("#lightboxOverlay");this.$outerContainer=this.$lightbox.find(".lb-outerContainer");this.$container=
this.$lightbox.find(".lb-container");this.containerTopPadding=parseInt(this.$container.css("padding-top"),10);this.containerRightPadding=parseInt(this.$container.css("padding-right"),10);this.containerBottomPadding=parseInt(this.$container.css("padding-bottom"),10);this.containerLeftPadding=parseInt(this.$container.css("padding-left"),10);if(this.options.showThumbnails){var $thumbnailContainer=$("\x3cdiv class\x3d'lb-thumbContainer'\x3e\x3c/div\x3e");$thumbnailContainer.insertBefore(this.$lightbox.find(".lb-prev"));
this.$thumbnailContainer=$(".lb-thumbContainer")}this.$overlay.hide().on("click",function(){self.end();return false});this.$lightbox.hide().on("click",function(event){if($(event.target).attr("id")==="lightbox")self.end();return false});this.$outerContainer.on("click",function(event){if($(event.target).attr("id")==="lightbox")self.end();return false});this.$lightbox.find(".lb-prev").on("click",function(){if(self.currentImageIndex===0)self.changeImage(self.album.length-1);else self.changeImage(self.currentImageIndex-
1);return false});this.$lightbox.find(".lb-next").on("click",function(){if(self.currentImageIndex===self.album.length-1)self.changeImage(0);else self.changeImage(self.currentImageIndex+1);return false});this.$lightbox.find(".lb-loader, .lb-close").on("click",function(){self.end();return false})};Lightbox.prototype.start=function($link){this.build();var self=this;var $window=$(window);$window.on("resize",$.proxy(this.sizeOverlay,this));$("select, object, embed").css({visibility:"hidden"});this.sizeOverlay();
this.album=[];var imageNumber=0;function addToAlbum($link){self.album.push({link:$link.attr("href"),headline:$link.attr("data-headline")||$link.attr("headline"),title:$link.attr("data-title")||$link.attr("title")})}var dataLightboxValue=$link.attr("data-lightbox");var $links;if(dataLightboxValue){$links=$link.parent().find($link.prop("tagName")+'[data-lightbox\x3d"'+dataLightboxValue+'"]');for(var i=0;i<$links.length;i=++i){addToAlbum($($links[i]));if($links[i]===$link[0])imageNumber=i}}else if($link.attr("rel")===
"lightbox")addToAlbum($link);else{$links=$($link.prop("tagName")+'[rel\x3d"'+$link.attr("rel")+'"]');for(var j=0;j<$links.length;j=++j){addToAlbum($($links[j]));if($links[j]===$link[0])imageNumber=j}}if(this.options.showThumbnails&&$(".lb-thumb").length===0){var thumbColumn='\x3cdiv class\x3d"lb-thumbColumn"\x3e';for(var t=0;t<this.album.length;t++){var source=this.album[t].link;if(t%10===9)thumbColumn+='\x3cimg class\x3d"lb-thumb"  data-thumb-value\x3d'+t+' src\x3d"'+source+'"\x3e\x3c/div\x3e\x3cdiv class\x3d"lb-thumbColumn"\x3e';
else thumbColumn+='\x3cimg class\x3d"lb-thumb"  data-thumb-value\x3d'+t+' src\x3d"'+source+'"\x3e'}this.$thumbnailContainer.append(thumbColumn);var columnWidths=0;$(".lb-thumbColumn").each(function(){var columns=$(this).width();columnWidths+=columns});var thumbnailContainerLeftMargin=columnWidths+40;this.$thumbnailContainer.css("margin-left",-Math.abs(thumbnailContainerLeftMargin))}if(this.options.showThumbnails&&$(".lb-thumb").length>1){this.$thumb=this.$lightbox.find(".lb-thumb");this.$lightbox.find(".lb-thumb").each(function(){var thumbData=
$(this).attr("data-thumb-value");if(thumbData==imageNumber)$(this).addClass("active")});this.$lightbox.find(".lb-thumb").on("click",function(){$(".lb-thumb").removeClass("active");$(this).addClass("active");var thumbData=$(this).attr("data-thumb-value");var thumbInteger=parseInt(thumbData);self.changeImage(thumbInteger);return false})}else if(this.options.showThumbnails&&$(".lb-thumb").length<=1)this.$thumbnailContainer.hide();var top=$window.scrollTop()+this.options.positionFromTop;var left=$window.scrollLeft();
this.$lightbox.css({top:top+"px",left:left+"px"}).fadeIn(this.options.fadeDuration);this.changeImage(imageNumber)};Lightbox.prototype.changeImage=function(imageNumber){var self=this;this.disableKeyboardNav();var $image=this.$lightbox.find(".lb-image");this.$overlay.fadeIn(this.options.fadeDuration);$(".lb-loader").fadeIn("slow");this.$lightbox.find(".lb-image, .lb-nav, .lb-prev, .lb-next, .lb-dataContainer, .lb-numbers, .lb-headline, .lb-caption").hide();this.$outerContainer.addClass("animating");
var preloader=new Image;preloader.onload=function(){var $preloader,imageHeight,imageWidth,maxImageHeight,maxImageWidth,windowHeight,windowWidth;$image.attr("src",self.album[imageNumber].link);$preloader=$(preloader);$image.width(preloader.width);$image.height(preloader.height);if(self.options.fitImagesInViewport){windowWidth=$(window).width();windowHeight=$(window).height();maxImageWidth=windowWidth-self.containerLeftPadding-self.containerRightPadding-100;maxImageHeight=windowHeight-self.containerTopPadding-
self.containerBottomPadding-120;if(preloader.width>maxImageWidth||preloader.height>maxImageHeight)if(preloader.width/maxImageWidth>preloader.height/maxImageHeight){imageWidth=maxImageWidth;imageHeight=parseInt(preloader.height/(preloader.width/imageWidth),10);$image.width(imageWidth);$image.height(imageHeight)}else{imageHeight=maxImageHeight;imageWidth=parseInt(preloader.width/(preloader.height/imageHeight),10);$image.width(imageWidth);$image.height(imageHeight)}}self.sizeContainer($image.width(),
$image.height())};preloader.src=this.album[imageNumber].link;this.currentImageIndex=imageNumber;if(this.options.showThumbnails&&$(".lb-thumb").length>1)this.$lightbox.find(".lb-thumb").each(function(){$(this).removeClass("active");var thumbData=$(this).attr("data-thumb-value");if(thumbData==imageNumber)$(this).addClass("active")})};Lightbox.prototype.sizeOverlay=function(){this.$overlay.width($(window).width()).height($(document).height())};Lightbox.prototype.sizeContainer=function(imageWidth,imageHeight){var self=
this;var oldWidth=this.$outerContainer.outerWidth();var oldHeight=this.$outerContainer.outerHeight();var newWidth=imageWidth+this.containerLeftPadding+this.containerRightPadding;var newHeight=imageHeight+this.containerTopPadding+this.containerBottomPadding;function postResize(){self.$lightbox.find(".lb-dataContainer").width(newWidth);self.$lightbox.find(".lb-prevLink").height(newHeight);self.$lightbox.find(".lb-nextLink").height(newHeight);self.showImage()}if(oldWidth!==newWidth||oldHeight!==newHeight)this.$outerContainer.animate({width:newWidth},
this.options.resizeDuration,"swing",function(){postResize()});else postResize()};Lightbox.prototype.showImage=function(){this.$lightbox.find(".lb-loader").hide();this.$lightbox.find(".lb-image").fadeIn("slow");this.updateNav();this.updateDetails();this.preloadNeighboringImages();this.enableKeyboardNav()};Lightbox.prototype.updateNav=function(){var alwaysShowNav=false;try{document.createEvent("TouchEvent");alwaysShowNav=this.options.alwaysShowNavOnTouchDevices?true:false}catch(e){}this.$lightbox.find(".lb-nav").show();
if(this.album.length>1)if(this.options.wrapAround){if(alwaysShowNav)this.$lightbox.find(".lb-prev, .lb-next").css("opacity","1");this.$lightbox.find(".lb-prev, .lb-next").show()}else{if(this.currentImageIndex>0){this.$lightbox.find(".lb-prev").show();if(alwaysShowNav)this.$lightbox.find(".lb-prev").css("opacity","1")}if(this.currentImageIndex<this.album.length-1){this.$lightbox.find(".lb-next").show();if(alwaysShowNav)this.$lightbox.find(".lb-next").css("opacity","1")}}};Lightbox.prototype.updateDetails=
function(){var self=this;if(typeof this.album[this.currentImageIndex].title!=="undefined"&&this.album[this.currentImageIndex].title!=="")this.$lightbox.find(".lb-caption").html(this.album[this.currentImageIndex].title).fadeIn("fast").find("a").on("click",function(event){location.href=$(this).attr("href")});if(typeof this.album[this.currentImageIndex].headline!=="undefined"&&this.album[this.currentImageIndex].headline!=="")this.$lightbox.find(".lb-headline").html(this.album[this.currentImageIndex].headline).fadeIn("fast");
if(this.album.length>1&&this.options.showImageNumberLabel)this.$lightbox.find(".lb-number").text(this.options.albumLabel(this.currentImageIndex+1,this.album.length)).fadeIn("fast");else this.$lightbox.find(".lb-number").hide();this.$outerContainer.removeClass("animating");this.$lightbox.find(".lb-dataContainer").fadeIn(this.options.resizeDuration,function(){return self.sizeOverlay()})};Lightbox.prototype.preloadNeighboringImages=function(){if(this.album.length>this.currentImageIndex+1){var preloadNext=
new Image;preloadNext.src=this.album[this.currentImageIndex+1].link}if(this.currentImageIndex>0){var preloadPrev=new Image;preloadPrev.src=this.album[this.currentImageIndex-1].link}};Lightbox.prototype.enableKeyboardNav=function(){$(document).on("keyup.keyboard",$.proxy(this.keyboardAction,this))};Lightbox.prototype.disableKeyboardNav=function(){$(document).off(".keyboard")};Lightbox.prototype.keyboardAction=function(event){var KEYCODE_ESC=27;var KEYCODE_LEFTARROW=37;var KEYCODE_RIGHTARROW=39;var keycode=
event.keyCode;var key=String.fromCharCode(keycode).toLowerCase();if(keycode===KEYCODE_ESC||key.match(/x|o|c/))this.end();else if(key==="p"||keycode===KEYCODE_LEFTARROW)if(this.currentImageIndex!==0)this.changeImage(this.currentImageIndex-1);else{if(this.options.wrapAround&&this.album.length>1)this.changeImage(this.album.length-1)}else if(key==="n"||keycode===KEYCODE_RIGHTARROW)if(this.currentImageIndex!==this.album.length-1)this.changeImage(this.currentImageIndex+1);else if(this.options.wrapAround&&
this.album.length>1)this.changeImage(0)};Lightbox.prototype.end=function(){this.disableKeyboardNav();$(window).off("resize",this.sizeOverlay);this.$lightbox.fadeOut(this.options.fadeDuration);this.$overlay.fadeOut(this.options.fadeDuration);$("select, object, embed").css({visibility:"visible"})};return Lightbox}();$(function(){var options=new LightboxOptions;var lightbox=new Lightbox(options)})}(window.$j);
(function($){$.fn.tableHeadFixer=function(param){return this.each(function(){table.call(this)});function table(){{var solveRightColspan=function(row,action){var fixColumn=settings.right;var inc=1;for(var i=1;i<=fixColumn;i=i+inc){var nth=inc>1?i-1:i;var cell=$(row).find("\x3e *:nth-last-child("+nth+")");var colspan=cell.prop("colspan");action(cell);inc=colspan}};var solverLeftColspan=function(row,action){var fixColumn=settings.left;var inc=1;for(var i=1;i<=fixColumn;i=i+inc){var nth=inc>1?i-1:i;var cell=
$(row).find("\x3e *:nth-child("+nth+")");var colspan=cell.prop("colspan");if(cell.cellPos().left<fixColumn)action(cell);inc=colspan}};var setBackground=function(elements){elements.each(function(k,element){var element=$(element);var parent=$(element).parent();var elementBackground=element.css("background-color");elementBackground=elementBackground=="transparent"||elementBackground=="rgba(0, 0, 0, 0)"?null:elementBackground;var parentBackground=parent.css("background-color");parentBackground=parentBackground==
"transparent"||parentBackground=="rgba(0, 0, 0, 0)"?null:parentBackground;var background=parentBackground?parentBackground:"white";background=elementBackground?elementBackground:background;element.css("background-color",background)})};var fixRight=function(){var table=$(settings.table);var fixColumn=settings.right;settings.rightColumns=$();var tr=table.find("tr");tr.each(function(k,row){solveRightColspan(row,function(cell){settings.rightColumns=settings.rightColumns.add(cell)})});var column=settings.rightColumns;
column.each(function(k,cell){var cell=$(cell);setBackground(cell);cell.css({"position":"relative"})})};var fixLeft=function(){var table=$(settings.table);$(table).parent().prepend("\x3cdiv class\x3d'shadow left'\x3e\x3c/div\x3e");settings.leftColumns=$();var tr=table.find("tr");tr.each(function(k,row){solverLeftColspan(row,function(cell){settings.leftColumns=settings.leftColumns.add(cell)})});var column=settings.leftColumns;column.each(function(k,cell){var cell=$(cell);setBackground(cell);cell.css({"position":"relative"})})};
var fixFoot=function(){var tfoot=$(settings.table).find("tfoot");var tr=tfoot.find("tr");var cells=tfoot.find("tr \x3e *");setBackground(cells);cells.css({"position":"relative"})};var fixHead=function(){var thead=$(settings.table).find("thead");if(thead>0){var tr=thead.find("tr");var cells=thead.find("tr \x3e *");$(thead).parent().parent().prepend("\x3cdiv class\x3d'shadow top'\x3e\x3c/div\x3e");setBackground(cells);cells.css({"position":"relative"})}else{var tbody=$(settings.table).find("tbody");
var tr=tbody.find("tr:first");var cells=tbody.find("tr:first \x3e *");$(tbody).parent().parent().prepend("\x3cdiv class\x3d'shadow top'\x3e\x3c/div\x3e");setBackground(cells);cells.css({"position":"relative"})}};var setParent=function(){var parent=$(settings.parent);var table=$(settings.table);parent.append(table);parent.css({"overflow-x":"auto","overflow-y":"auto"});parent.scroll(function(){var scrollWidth=parent[0].scrollWidth;var clientWidth=parent[0].clientWidth;var scrollHeight=parent[0].scrollHeight;
var clientHeight=parent[0].clientHeight;var top=parent.scrollTop();var left=parent.scrollLeft();if(settings.head){var theadLength=this.find("thead").length;switch(theadLength){case 0:this.find("tbody tr:first-child \x3e *").css("top",top);var width=this.outerWidth();var outerHeight=this.find("tbody tr:first-child \x3e *").outerHeight();var topHeight=parseInt(this.find("tbody tr:first-child \x3e *").css("top"));var scrollingHeight=outerHeight+topHeight;this.parent().find(".shadow.top").width(width).css("top",
scrollingHeight);break;case 1:this.find("thead tr \x3e *").css("top",top);var width=this.outerWidth();var outerHeight=this.find("thead tr \x3e *").outerHeight();var topHeight=parseInt(this.find("thead tr \x3e *").css("top"));var scrollingHeight=outerHeight+topHeight;this.parent().find(".shadow.top").width(width).css("top",scrollingHeight);break;default:return}}if(settings.foot)this.find("tfoot tr \x3e *").css("bottom",scrollHeight-clientHeight-top);if(settings.left>0){settings.leftColumns.css("left",
left);var leftWidth=parseInt(settings.leftColumns.css("left"));var outerWidth=$(settings.leftColumns).outerWidth();var scrollingWidth=leftWidth+outerWidth;this.parent().find(".shadow.left").css("left",scrollingWidth)}if(settings.right>0)settings.rightColumns.css("right",scrollWidth-clientWidth-left)}.bind(table))};var setCorner=function(){var table=$(settings.table);if(settings.head){if(settings.left>0){var tr=table.find("thead tr");tr.each(function(k,row){solverLeftColspan(row,function(cell){$(cell).css("z-index",
settings["z-index"]+1)})})}if(settings.right>0){var tr=table.find("thead tr");tr.each(function(k,row){solveRightColspan(row,function(cell){$(cell).css("z-index",settings["z-index"]+1)})})}}if(settings.foot){if(settings.left>0){var tr=table.find("tfoot tr");tr.each(function(k,row){solverLeftColspan(row,function(cell){$(cell).css("z-index",settings["z-index"])})})}if(settings.right>0){var tr=table.find("tfoot tr");tr.each(function(k,row){solveRightColspan(row,function(cell){$(cell).css("z-index",settings["z-index"])})})}}};
var defaults={head:true,foot:false,left:0,right:0,"z-index":0};var settings=$.extend({},defaults,param);settings.table=this;settings.parent=$(settings.table).parent();setParent();if(settings.head===true)fixHead();if(settings.foot===true)fixFoot();if(settings.left>0)fixLeft();if(settings.right>0)fixRight();setCorner();$(settings.parent).trigger("scroll");$(window).resize(function(){$(settings.parent).trigger("scroll")})}}}})(jQuery);
(function($){function scanTable($table){var m=[];$table.children("tr").each(function(y,row){$(row).children("td, th").each(function(x,cell){var $cell=$(cell),cspan=$cell.attr("colspan")|0,rspan=$cell.attr("rowspan")|0,tx,ty;cspan=cspan?cspan:1;rspan=rspan?rspan:1;for(;m[y]&&m[y][x];++x);for(tx=x;tx<x+cspan;++tx)for(ty=y;ty<y+rspan;++ty){if(!m[ty])m[ty]=[];m[ty][tx]=true}var pos={top:y,left:x};$cell.data("cellPos",pos)})})}$.fn.cellPos=function(rescan){var $cell=this.first(),pos=$cell.data("cellPos");
if(!pos||rescan){var $table=$cell.closest("table, thead, tbody, tfoot");scanTable($table)}pos=$cell.data("cellPos");return pos}})(jQuery);
!function($){$.fn.cvc=function(options){var o=$.extend({hoverClass:"hover-cvc",btnClass:"btn",btnClassToggle:"btn-primary",active:1},options);return this.each(function(){var $this=$(this),activeDefault=o.active+1;$this.find("tr :nth-child("+activeDefault+")").addClass(o.hoverClass).find("."+o.btnClass).addClass(o.btnClassToggle);$this.find("th,td").hover(function(){var thisIndex=$(this).parent("tr").children().index(this)+1;if(thisIndex>1&&$(this).is(":not(."+o.hoverClass+")")){$this.find("."+o.hoverClass).removeClass(o.hoverClass).find("."+
o.btnClass).removeClass(o.btnClassToggle);$this.find("tr :nth-child("+thisIndex+")").addClass(o.hoverClass).find("."+o.btnClass).addClass(o.btnClassToggle)}})})}}(window.$j);
!function($){$.fn.sliderCarousel=function(){return this.each(function(){var $carousel=$(this);if($carousel.hasClass("slider-carousel-init"))return;$carousel.addClass("slider-carousel-init");var $thumbs=$(".thumb",$carousel);var $slides=$(".slide",$carousel);$slides.each(function(index,element){var $slide=$(this);var $img=$("img",this);$img.on("load",function(){calculateRatios()}).each(function(){if(this.complete)$(this).trigger("load")});$(window).resize(calculateRatios);function calculateRatios(){var slideWidth=
$slide.width(),slideHeight=$slide.height();var slideRatio=slideWidth/slideHeight;var width=$img.width(),height=$img.height();var ratio=width/height;$img.attr("data-ratio",ratio);$slide.removeClass("carousel-image-same carousel-image-wider carousel-image-taller");if(ratio==slideRatio)$slide.addClass("carousel-image-same");else if(ratio>slideRatio)$slide.addClass("carousel-image-wider");else $slide.addClass("carousel-image-taller")}});$thumbs.click(function(e){e.preventDefault();$thumbs.removeClass("active");
$(this).addClass("active");var myIndex=$(this).index();$slides.removeClass("active");$slides.eq(myIndex).addClass("active")})})}}(window.$j);
function ObjectFitIE(config){this.config=config|{};this.classes=".image-cover,.image-contain,.textimage-cover,.textimage-contain".split(",");this.getNatural=function(DOMelement){var response;var hasImageContainer=!!$(DOMelement).closest(".image-container").length;if(hasImageContainer){var div=$(DOMelement).closest(".image-container");response={naturalHeight:$(div).outerHeight(),naturalWidth:div.outerWidth()}}else{var img=new Image;img.src=DOMelement.src;response={naturalHeight:img.height,naturalWidth:"100%"}}return response};
this.isIE=function(){return navigator.userAgent.search(/(Trident)|(MSIE)/)!=-1};this.getTargets=function(){return $(this.classes.join(","))};this.wrapImg=function(img){var wrap=$('\x3cdiv class\x3d"image-fit-wrap"/\x3e');$(img).parent().append(wrap);return wrap};this.setBGProps=function(doppelGanger,img){var coverYContain=$(img).prop("class")&&$(img).prop("class").indexOf("contain")!=-1?"contain":"cover";var filterOption=coverYContain=="contain"?"":"progid:DXImageTransform.Microsoft.AlphaImageLoader(src\x3d'"+
img.src+"', sizingMethod\x3d'scale')";var styles={"background-image":"url("+img.src+")","background-size":coverYContain,"height":this.getNatural(img).naturalHeight,"width":this.getNatural(img).naturalWidth};if(filterOption&&navigator.userAgent.indexOf("MSIE 8")!=-1){styles["filter"]=filterOption;styles["background"]="none"}$(doppelGanger).css(styles)};this.swapMundo=function(doppelGanger,img){$(img).hide();$(doppelGanger).show()};this.fix=function(img){var doppelGanger=this.wrapImg(img);this.setBGProps(doppelGanger,
img);this.swapMundo(doppelGanger,img)};this.initFix=function(){var _self=this;if(this.isIE()){var targets=this.getTargets();$(targets).each(function(ind,img){_self.fix(img)})}};this.initFix()}$(document).ready(function(){ObjectFitIE()});$.fn.fillIt=function(){function getNatural(DOMelement){var img=new Image;img.src=DOMelement.src;return img.height}$.each(this,function(){var isIE8=navigator.userAgent.indexOf("MSIE 8.0")!=-1?1:0;$(this).attr("height",isIE8?getNatural(this):this.naturalHeight)})};