/*
 HTML5 Shiv 3.7.3 @afarkas @jdalton @jon_neal @rem MIT/GPL2 Licensed
 matchMedia() polyfill - Test a CSS media type/query in JS. Authors & copyright (c) 2012: Scott Jehl, Paul Irish, Nicholas Zakas. Dual MIT/BSD license  picturefill - v3.0.2 - 2016-02-12
 https://scottjehl.github.io/picturefill/
 Copyright (c) 2016 https://github.com/scottjehl/picturefill/blob/master/Authors.txt; Licensed MIT
 Gecko-Picture - v1.0
 https://github.com/scottjehl/picturefill/tree/3.0/src/plugins/gecko-picture
 Firefox's early picture implementation (prior to FF41) is static and does
 not react to viewport changes. This tiny module fixes this.
 Picturefill - v3.0.2
 http://scottjehl.github.io/picturefill
 Copyright (c) 2015 https://github.com/scottjehl/picturefill/blob/master/Authors.txt;
  License: MIT
*/
(function(CQ){CQ.WCM=CQ.WCM||{};CQ.WCM.Image=CQ.WCM.Image||function(){var self={};var CONST={MAP_SELECTOR:".cq-wcm-foundation-image-map"};self.handleResize=function(){var elements=document.querySelectorAll(CONST.MAP_SELECTOR);Array.prototype.forEach.call(elements,function(el){if(!el.getAttribute("usemap"))return;var imgSrc=el.getAttribute("src"),onLoadImg=document.createElement("img");onLoadImg.addEventListener("load",function(){var imgWidth=el.getAttribute("width")||el.naturalWidth,imgHeight=el.getAttribute("height")||
el.naturalHeight;if(!imgWidth||!imgHeight){var tempImage=new Image;tempImage.src=imgSrc;if(!imgWidth)imgWidth=tempImage.width;if(!imgHeight)imgHeight=tempImage.height}var relWidth=el.offsetWidth/100,relHeight=el.offsetHeight/100,map=el.getAttribute("usemap");map=map.replace("#","");var maps=document.querySelectorAll('map[name\x3d"'+map+'"]');Array.prototype.forEach.call(maps,function(mapEl){var areas=mapEl.querySelectorAll("area");Array.prototype.forEach.call(areas,function(areaEl){if(!areaEl.dataset.coords)areaEl.dataset.coords=
areaEl.getAttribute("coords");var coords=areaEl.dataset.coords.split(","),relCoords=new Array(coords.length);for(var i=0;i<coords.length;++i)if(i%2==0)relCoords[i]=parseInt(coords[i]/imgWidth*100*relWidth);else relCoords[i]=parseInt(coords[i]/imgHeight*100*relHeight);areaEl.setAttribute("coords",relCoords.toString())})})});onLoadImg.setAttribute("src",imgSrc)})};return self}();var addEventListener=window.addEventListener||window.attachEvent,MutationObserver=window.MutationObserver||window.WebKitMutationObserver||
window.MozMutationObserver,mutationConfig={attributes:true},observer=new MutationObserver(function(mutations){mutations.forEach(function(){CQ.WCM.Image.handleResize()})});addEventListener("resize",CQ.WCM.Image.handleResize);observer.observe(document,mutationConfig);CQ.WCM.Image.handleResize()})(CQ);
(function($){$.fn.rwdImageMaps=function(){var $img=this;var rwdImageMap=function(){$img.each(function(){if(typeof $(this).attr("usemap")=="undefined")return;var that=this,$that=$(that);$("\x3cimg /\x3e").on("load",function(){var attrW="width",attrH="height",w=$that.attr(attrW),h=$that.attr(attrH);if(!w||!h){var temp=new Image;temp.src=$that.attr("src");if(!w)w=temp.width;if(!h)h=temp.height}var wPercent=$that.width()/100,hPercent=$that.height()/100,map=$that.attr("usemap").replace("#",""),c="coords";
$('map[name\x3d"'+map+'"]').find("area").each(function(){var $this=$(this);if(!$this.data(c))$this.data(c,$this.attr(c));var coords=$this.data(c).split(","),coordsPercent=new Array(coords.length);for(var i=0;i<coordsPercent.length;++i)if(i%2===0)coordsPercent[i]=parseInt(coords[i]/w*100*wPercent);else coordsPercent[i]=parseInt(coords[i]/h*100*hPercent);$this.attr(c,coordsPercent.toString())})}).attr("src",$that.attr("src"))})};$(window).resize(rwdImageMap).trigger("resize");return this}})(jQuery);
(function(document,$){var MutationObserver=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver,mutationConfig={attributes:true},observer=new MutationObserver(function(mutations){mutations.forEach(function(){bindPlugin()})});$(function(){bindPlugin();observer.observe(document.documentElement,mutationConfig)});function bindPlugin(){$("div[id^\x3d'cq-image-jsp-']").each(function(i,el){$("img[usemap]",el).rwdImageMaps()})}})(document,$CQ);
(function($){$(function(){function errorLog(error,message){try{if($.cq.isAuthor()||window.location.hash=="#debug"){if(typeof console!="undefined"&&typeof console.log!="undefined"){console.log(error);console.log(message)}alert(error.name+":\n"+error.message+".\n"+message+".")}}catch(e){}}try{var removeHash=function(context){try{if(window.location.hash.length>0&&$(window.location.hash,context).length>0)window.location=(window.location+"").replace(window.location.hash,"")}catch(e){errorLog(e,"Could not remove hash")}};
var fadingSpeed=$.browser.msie?0:250;try{$(".cq-carousel").each(function(){var carousel=$(this);var playDelay=+$("var[title\x3d'play-delay']",this).text();if(!playDelay)playDelay=6E3;var slidingSpeed=+$("var[title\x3d'transition-time']",this).text();if(!slidingSpeed)slidingSpeed=1E3;var banners=$(".cq-carousel-banners",this);var switcher=$(".cq-carousel-banner-switch",this);var links=switcher.find("a");var items=$(".cq-carousel-banner-item",this);var width=items.outerWidth();var itemActive=items.filter(":first");
var itemPrevious=null;var interval=null;var i=0;var ctlPrev=$("a.cq-carousel-control-prev",this);ctlPrev.click(function(){if(ctlPrev.is(".cq-carousel-active"))$(links[(i+links.length-1)%links.length]).click();return false});var ctlNext=$("a.cq-carousel-control-next",this);ctlNext.click(function(){if(ctlNext.is(".cq-carousel-active"))$(links[(i+1)%links.length]).click();return false});if(links.length>1)ctlNext.addClass("cq-carousel-active");function play(){stop();if(playDelay>0)interval=setInterval(function(){$(links[(i+
1)%links.length]).click()},playDelay)}function stop(){if(interval!==null){clearInterval(interval);interval=null}}if(fadingSpeed||$.browser.version>6)itemActive.css("left",0);else itemActive.show();links.click(function(){var link=$(this);var itemNew=items.filter(link.attr("href"));var j=itemNew.prevAll().length;var direction=j>i||interval!==null?1:-1;if(!link.is(".cq-carousel-active")){links.removeClass("cq-carousel-active");link.addClass("cq-carousel-active");if(itemActive.is(":animated")){itemActive.stop(true,
true);itemPrevious.stop(true,true)}if(fadingSpeed){itemNew.css({"left":direction*width}).animate({"left":0,"opacity":1},slidingSpeed);itemActive.animate({"left":-direction*width,"opacity":0},slidingSpeed)}else if($.browser.version>6){itemNew.css({"left":direction*width,opacity:1}).animate({"left":0},slidingSpeed);itemActive.animate({"left":-direction*width},slidingSpeed)}else{itemNew.fadeIn();itemActive.fadeOut()}itemPrevious=itemActive;itemActive=itemNew;i=j;if(i>0)ctlPrev.addClass("cq-carousel-active");
else ctlPrev.removeClass("cq-carousel-active");if(i<links.length-1)ctlNext.addClass("cq-carousel-active");else ctlNext.removeClass("cq-carousel-active")}return false}).each(function(){var link=$(this);link.attr("title",link.text())}).filter(":first").addClass("cq-carousel-active");play();carousel.hover(function(){stop();ctlPrev.fadeIn();ctlNext.fadeIn()},function(){play();ctlPrev.fadeOut();ctlNext.fadeOut()});removeHash(this)})}catch(e){errorLog(e,"Could not initialize the banners")}}catch(e$0){errorLog(e$0,
"Init failed")}})})($CQ||$);
(function($){var $event=$.event,$special,resizeTimeout;$special=$event.special.debouncedresize={setup:function(){$(this).on("resize",$special.handler)},teardown:function(){$(this).off("resize",$special.handler)},handler:function(event,execAsap){var context=this,args=arguments,dispatch=function(){event.type="debouncedresize";$event.dispatch.apply(context,args)};if(resizeTimeout)clearTimeout(resizeTimeout);execAsap?dispatch():resizeTimeout=setTimeout(dispatch,$special.threshold)},threshold:150}})($);
window.matchMedia=window.matchMedia||function(doc,undefined){var bool,docElem=doc.documentElement,refNode=docElem.firstElementChild||docElem.firstChild,fakeBody=doc.createElement("body"),div=doc.createElement("div");div.id="mq-test-1";div.style.cssText="position:absolute;top:-100em";fakeBody.style.background="none";fakeBody.appendChild(div);return function(q){div.innerHTML='\x26shy;\x3cstyle media\x3d"'+q+'"\x3e #mq-test-1 { width: 42px; }\x3c/style\x3e';docElem.insertBefore(fakeBody,refNode);bool=
div.offsetWidth===42;docElem.removeChild(fakeBody);return{matches:bool,media:q}}}(document);
(function(window){var ua=navigator.userAgent;if(window.HTMLPictureElement&&(/ecko/.test(ua)&&ua.match(/rv:(\d+)/)&&RegExp.$1<45))addEventListener("resize",function(){var timer;var dummySrc=document.createElement("source");var fixRespimg=function(img){var source,sizes;var picture=img.parentNode;if(picture.nodeName.toUpperCase()==="PICTURE"){source=dummySrc.cloneNode();picture.insertBefore(source,picture.firstElementChild);setTimeout(function(){picture.removeChild(source)})}else if(!img._pfLastSize||
img.offsetWidth>img._pfLastSize){img._pfLastSize=img.offsetWidth;sizes=img.sizes;img.sizes+=",100vw";setTimeout(function(){img.sizes=sizes})}};var findPictureImgs=function(){var i;var imgs=document.querySelectorAll("picture \x3e img, img[srcset][sizes]");for(i=0;i<imgs.length;i++)fixRespimg(imgs[i])};var onResize=function(){clearTimeout(timer);timer=setTimeout(findPictureImgs,99)};var mq=window.matchMedia&&matchMedia("(orientation: landscape)");var init=function(){onResize();if(mq&&mq.addListener)mq.addListener(onResize)};
dummySrc.srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw\x3d\x3d";if(/^[c|i]|d$/.test(document.readyState||""))init();else document.addEventListener("DOMContentLoaded",init);return onResize}())})(window);
(function(window,document,undefined){document.createElement("picture");var warn,eminpx,alwaysCheckWDescriptor,evalId;var pf={};var isSupportTestReady=false;var noop=function(){};var image=document.createElement("img");var getImgAttr=image.getAttribute;var setImgAttr=image.setAttribute;var removeImgAttr=image.removeAttribute;var docElem=document.documentElement;var types={};var cfg={algorithm:""};var srcAttr="data-pfsrc";var srcsetAttr=srcAttr+"set";var ua=navigator.userAgent;var supportAbort=/rident/.test(ua)||
/ecko/.test(ua)&&ua.match(/rv:(\d+)/)&&RegExp.$1>35;var curSrcProp="currentSrc";var regWDesc=/\s+\+?\d+(e\d+)?w/;var regSize=/(\([^)]+\))?\s*(.+)/;var setOptions=window.picturefillCFG;var baseStyle="position:absolute;left:0;visibility:hidden;display:block;padding:0;border:none;font-size:1em;width:1em;overflow:hidden;clip:rect(0px, 0px, 0px, 0px)";var fsCss="font-size:100%!important;";var isVwDirty=true;var cssCache={};var sizeLengthCache={};var DPR=window.devicePixelRatio;var units={px:1,"in":96};
var anchor=document.createElement("a");var alreadyRun=false;var regexLeadingSpaces=/^[ \t\n\r\u000c]+/,regexLeadingCommasOrSpaces=/^[, \t\n\r\u000c]+/,regexLeadingNotSpaces=/^[^ \t\n\r\u000c]+/,regexTrailingCommas=/[,]+$/,regexNonNegativeInteger=/^\d+$/,regexFloatingPoint=/^-?(?:[0-9]+|[0-9]*\.[0-9]+)(?:[eE][+-]?[0-9]+)?$/;var on=function(obj,evt,fn,capture){if(obj.addEventListener)obj.addEventListener(evt,fn,capture||false);else if(obj.attachEvent)obj.attachEvent("on"+evt,fn)};var memoize=function(fn){var cache=
{};return function(input){if(!(input in cache))cache[input]=fn(input);return cache[input]}};function isSpace(c){return c===" "||c==="\t"||c==="\n"||c==="\f"||c==="\r"}var evalCSS=function(){var regLength=/^([\d\.]+)(em|vw|px)$/;var replace=function(){var args=arguments,index=0,string=args[0];while(++index in args)string=string.replace(args[index],args[++index]);return string};var buildStr=memoize(function(css){return"return "+replace((css||"").toLowerCase(),/\band\b/g,"\x26\x26",/,/g,"||",/min-([a-z-\s]+):/g,
"e.$1\x3e\x3d",/max-([a-z-\s]+):/g,"e.$1\x3c\x3d",/calc([^)]+)/g,"($1)",/(\d+[\.]*[\d]*)([a-z]+)/g,"($1 * e.$2)",/^(?!(e.[a-z]|[0-9\.&=|><\+\-\*\(\)\/])).*/ig,"")+";"});return function(css,length){var parsedLength;if(!(css in cssCache)){cssCache[css]=false;if(length&&(parsedLength=css.match(regLength)))cssCache[css]=parsedLength[1]*units[parsedLength[2]];else try{cssCache[css]=(new Function("e",buildStr(css)))(units)}catch(e){}}return cssCache[css]}}();var setResolution=function(candidate,sizesattr){if(candidate.w){candidate.cWidth=
pf.calcListLength(sizesattr||"100vw");candidate.res=candidate.w/candidate.cWidth}else candidate.res=candidate.d;return candidate};var picturefill=function(opt){if(!isSupportTestReady)return;var elements,i,plen;var options=opt||{};if(options.elements&&options.elements.nodeType===1)if(options.elements.nodeName.toUpperCase()==="IMG")options.elements=[options.elements];else{options.context=options.elements;options.elements=null}elements=options.elements||pf.qsa(options.context||document,options.reevaluate||
options.reselect?pf.sel:pf.selShort);if(plen=elements.length){pf.setupRun(options);alreadyRun=true;for(i=0;i<plen;i++)pf.fillImg(elements[i],options);pf.teardownRun(options)}};warn=window.console&&console.warn?function(message){console.warn(message)}:noop;if(!(curSrcProp in image))curSrcProp="src";types["image/jpeg"]=true;types["image/gif"]=true;types["image/png"]=true;function detectTypeSupport(type,typeUri){var image=new window.Image;image.onerror=function(){types[type]=false;picturefill()};image.onload=
function(){types[type]=image.width===1;picturefill()};image.src=typeUri;return"pending"}types["image/svg+xml"]=document.implementation.hasFeature("http://www.w3.org/TR/SVG11/feature#Image","1.1");function updateMetrics(){isVwDirty=false;DPR=window.devicePixelRatio;cssCache={};sizeLengthCache={};pf.DPR=DPR||1;units.width=Math.max(window.innerWidth||0,docElem.clientWidth);units.height=Math.max(window.innerHeight||0,docElem.clientHeight);units.vw=units.width/100;units.vh=units.height/100;evalId=[units.height,
units.width,DPR].join("-");units.em=pf.getEmValue();units.rem=units.em}function chooseLowRes(lowerValue,higherValue,dprValue,isCached){var bonusFactor,tooMuch,bonus,meanDensity;if(cfg.algorithm==="saveData")if(lowerValue>2.7)meanDensity=dprValue+1;else{tooMuch=higherValue-dprValue;bonusFactor=Math.pow(lowerValue-.6,1.5);bonus=tooMuch*bonusFactor;if(isCached)bonus+=.1*bonusFactor;meanDensity=lowerValue+bonus}else meanDensity=dprValue>1?Math.sqrt(lowerValue*higherValue):lowerValue;return meanDensity>
dprValue}function applyBestCandidate(img){var srcSetCandidates;var matchingSet=pf.getSet(img);var evaluated=false;if(matchingSet!=="pending"){evaluated=evalId;if(matchingSet){srcSetCandidates=pf.setRes(matchingSet);pf.applySetCandidate(srcSetCandidates,img)}}img[pf.ns].evaled=evaluated}function ascendingSort(a,b){return a.res-b.res}function setSrcToCur(img,src,set){var candidate;if(!set&&src){set=img[pf.ns].sets;set=set&&set[set.length-1]}candidate=getCandidateForSrc(src,set);if(candidate){src=pf.makeUrl(src);
img[pf.ns].curSrc=src;img[pf.ns].curCan=candidate;if(!candidate.res)setResolution(candidate,candidate.set.sizes)}return candidate}function getCandidateForSrc(src,set){var i,candidate,candidates;if(src&&set){candidates=pf.parseSet(set);src=pf.makeUrl(src);for(i=0;i<candidates.length;i++)if(src===pf.makeUrl(candidates[i].url)){candidate=candidates[i];break}}return candidate}function getAllSourceElements(picture,candidates){var i,len,source,srcset;var sources=picture.getElementsByTagName("source");for(i=
0,len=sources.length;i<len;i++){source=sources[i];source[pf.ns]=true;srcset=source.getAttribute("srcset");if(srcset)candidates.push({srcset:srcset,media:source.getAttribute("media"),type:source.getAttribute("type"),sizes:source.getAttribute("sizes")})}}function parseSrcset(input,set){function collectCharacters(regEx){var chars,match=regEx.exec(input.substring(pos));if(match){chars=match[0];pos+=chars.length;return chars}}var inputLength=input.length,url,descriptors,currentDescriptor,state,c,pos=0,
candidates=[];function parseDescriptors(){var pError=false,w,d,h,i,candidate={},desc,lastChar,value,intVal,floatVal;for(i=0;i<descriptors.length;i++){desc=descriptors[i];lastChar=desc[desc.length-1];value=desc.substring(0,desc.length-1);intVal=parseInt(value,10);floatVal=parseFloat(value);if(regexNonNegativeInteger.test(value)&&lastChar==="w"){if(w||d)pError=true;if(intVal===0)pError=true;else w=intVal}else if(regexFloatingPoint.test(value)&&lastChar==="x"){if(w||d||h)pError=true;if(floatVal<0)pError=
true;else d=floatVal}else if(regexNonNegativeInteger.test(value)&&lastChar==="h"){if(h||d)pError=true;if(intVal===0)pError=true;else h=intVal}else pError=true}if(!pError){candidate.url=url;if(w)candidate.w=w;if(d)candidate.d=d;if(h)candidate.h=h;if(!h&&!d&&!w)candidate.d=1;if(candidate.d===1)set.has1x=true;candidate.set=set;candidates.push(candidate)}}function tokenize(){collectCharacters(regexLeadingSpaces);currentDescriptor="";state="in descriptor";while(true){c=input.charAt(pos);if(state==="in descriptor")if(isSpace(c)){if(currentDescriptor){descriptors.push(currentDescriptor);
currentDescriptor="";state="after descriptor"}}else if(c===","){pos+=1;if(currentDescriptor)descriptors.push(currentDescriptor);parseDescriptors();return}else if(c==="("){currentDescriptor=currentDescriptor+c;state="in parens"}else if(c===""){if(currentDescriptor)descriptors.push(currentDescriptor);parseDescriptors();return}else currentDescriptor=currentDescriptor+c;else if(state==="in parens")if(c===")"){currentDescriptor=currentDescriptor+c;state="in descriptor"}else if(c===""){descriptors.push(currentDescriptor);
parseDescriptors();return}else currentDescriptor=currentDescriptor+c;else if(state==="after descriptor")if(isSpace(c));else if(c===""){parseDescriptors();return}else{state="in descriptor";pos-=1}pos+=1}}while(true){collectCharacters(regexLeadingCommasOrSpaces);if(pos>=inputLength)return candidates;url=collectCharacters(regexLeadingNotSpaces);descriptors=[];if(url.slice(-1)===","){url=url.replace(regexTrailingCommas,"");parseDescriptors()}else tokenize()}}function parseSizes(strValue){var regexCssLengthWithUnits=
/^(?:[+-]?[0-9]+|[0-9]*\.[0-9]+)(?:[eE][+-]?[0-9]+)?(?:ch|cm|em|ex|in|mm|pc|pt|px|rem|vh|vmin|vmax|vw)$/i;var regexCssCalc=/^calc\((?:[0-9a-z \.\+\-\*\/\(\)]+)\)$/i;var i;var unparsedSizesList;var unparsedSizesListLength;var unparsedSize;var lastComponentValue;var size;function parseComponentValues(str){var chrctr;var component="";var componentArray=[];var listArray=[];var parenDepth=0;var pos=0;var inComment=false;function pushComponent(){if(component){componentArray.push(component);component=""}}
function pushComponentArray(){if(componentArray[0]){listArray.push(componentArray);componentArray=[]}}while(true){chrctr=str.charAt(pos);if(chrctr===""){pushComponent();pushComponentArray();return listArray}else if(inComment)if(chrctr==="*"&&str[pos+1]==="/"){inComment=false;pos+=2;pushComponent();continue}else{pos+=1;continue}else if(isSpace(chrctr))if(str.charAt(pos-1)&&isSpace(str.charAt(pos-1))||!component){pos+=1;continue}else if(parenDepth===0){pushComponent();pos+=1;continue}else chrctr=" ";
else if(chrctr==="(")parenDepth+=1;else if(chrctr===")")parenDepth-=1;else if(chrctr===","){pushComponent();pushComponentArray();pos+=1;continue}else if(chrctr==="/"&&str.charAt(pos+1)==="*"){inComment=true;pos+=2;continue}component=component+chrctr;pos+=1}}function isValidNonNegativeSourceSizeValue(s){if(regexCssLengthWithUnits.test(s)&&parseFloat(s)>=0)return true;if(regexCssCalc.test(s))return true;if(s==="0"||s==="-0"||s==="+0")return true;return false}unparsedSizesList=parseComponentValues(strValue);
unparsedSizesListLength=unparsedSizesList.length;for(i=0;i<unparsedSizesListLength;i++){unparsedSize=unparsedSizesList[i];lastComponentValue=unparsedSize[unparsedSize.length-1];if(isValidNonNegativeSourceSizeValue(lastComponentValue)){size=lastComponentValue;unparsedSize.pop()}else continue;if(unparsedSize.length===0)return size;unparsedSize=unparsedSize.join(" ");if(!pf.matchesMedia(unparsedSize))continue;return size}return"100vw"}pf.ns=("pf"+(new Date).getTime()).substr(0,9);pf.supSrcset="srcset"in
image;pf.supSizes="sizes"in image;pf.supPicture=!!window.HTMLPictureElement;if(pf.supSrcset&&pf.supPicture&&!pf.supSizes)(function(image2){image.srcset="data:,a";image2.src="data:,a";pf.supSrcset=image.complete===image2.complete;pf.supPicture=pf.supSrcset&&pf.supPicture})(document.createElement("img"));if(pf.supSrcset&&!pf.supSizes)(function(){var width2="data:image/gif;base64,R0lGODlhAgABAPAAAP///wAAACH5BAAAAAAALAAAAAACAAEAAAICBAoAOw\x3d\x3d";var width1="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw\x3d\x3d";
var img=document.createElement("img");var test=function(){var width=img.width;if(width===2)pf.supSizes=true;alwaysCheckWDescriptor=pf.supSrcset&&!pf.supSizes;isSupportTestReady=true;setTimeout(picturefill)};img.onload=test;img.onerror=test;img.setAttribute("sizes","9px");img.srcset=width1+" 1w,"+width2+" 9w";img.src=width1})();else isSupportTestReady=true;pf.selShort="picture\x3eimg,img[srcset]";pf.sel=pf.selShort;pf.cfg=cfg;pf.DPR=DPR||1;pf.u=units;pf.types=types;pf.setSize=noop;pf.makeUrl=memoize(function(src){anchor.href=
src;return anchor.href});pf.qsa=function(context,sel){return"querySelector"in context?context.querySelectorAll(sel):[]};pf.matchesMedia=function(){if(window.matchMedia&&(matchMedia("(min-width: 0.1em)")||{}).matches)pf.matchesMedia=function(media){return!media||matchMedia(media).matches};else pf.matchesMedia=pf.mMQ;return pf.matchesMedia.apply(this,arguments)};pf.mMQ=function(media){return media?evalCSS(media):true};pf.calcLength=function(sourceSizeValue){var value=evalCSS(sourceSizeValue,true)||
false;if(value<0)value=false;return value};pf.supportsType=function(type){return type?types[type]:true};pf.parseSize=memoize(function(sourceSizeStr){var match=(sourceSizeStr||"").match(regSize);return{media:match&&match[1],length:match&&match[2]}});pf.parseSet=function(set){if(!set.cands)set.cands=parseSrcset(set.srcset,set);return set.cands};pf.getEmValue=function(){var body;if(!eminpx&&(body=document.body)){var div=document.createElement("div"),originalHTMLCSS=docElem.style.cssText,originalBodyCSS=
body.style.cssText;div.style.cssText=baseStyle;docElem.style.cssText=fsCss;body.style.cssText=fsCss;body.appendChild(div);eminpx=div.offsetWidth;body.removeChild(div);eminpx=parseFloat(eminpx,10);docElem.style.cssText=originalHTMLCSS;body.style.cssText=originalBodyCSS}return eminpx||16};pf.calcListLength=function(sourceSizeListStr){if(!(sourceSizeListStr in sizeLengthCache)||cfg.uT){var winningLength=pf.calcLength(parseSizes(sourceSizeListStr));sizeLengthCache[sourceSizeListStr]=!winningLength?units.width:
winningLength}return sizeLengthCache[sourceSizeListStr]};pf.setRes=function(set){var candidates;if(set){candidates=pf.parseSet(set);for(var i=0,len=candidates.length;i<len;i++)setResolution(candidates[i],set.sizes)}return candidates};pf.setRes.res=setResolution;pf.applySetCandidate=function(candidates,img){if(!candidates.length)return;var candidate,i,j,length,bestCandidate,curSrc,curCan,candidateSrc,abortCurSrc;var imageData=img[pf.ns];var dpr=pf.DPR;curSrc=imageData.curSrc||img[curSrcProp];curCan=
imageData.curCan||setSrcToCur(img,curSrc,candidates[0].set);if(curCan&&curCan.set===candidates[0].set){abortCurSrc=supportAbort&&!img.complete&&curCan.res-.1>dpr;if(!abortCurSrc){curCan.cached=true;if(curCan.res>=dpr)bestCandidate=curCan}}if(!bestCandidate){candidates.sort(ascendingSort);length=candidates.length;bestCandidate=candidates[length-1];for(i=0;i<length;i++){candidate=candidates[i];if(candidate.res>=dpr){j=i-1;if(candidates[j]&&(abortCurSrc||curSrc!==pf.makeUrl(candidate.url))&&chooseLowRes(candidates[j].res,
candidate.res,dpr,candidates[j].cached))bestCandidate=candidates[j];else bestCandidate=candidate;break}}}if(bestCandidate){candidateSrc=pf.makeUrl(bestCandidate.url);imageData.curSrc=candidateSrc;imageData.curCan=bestCandidate;if(candidateSrc!==curSrc)pf.setSrc(img,bestCandidate);pf.setSize(img)}};pf.setSrc=function(img,bestCandidate){var origWidth;img.src=bestCandidate.url;if(bestCandidate.set.type==="image/svg+xml"){origWidth=img.style.width;img.style.width=img.offsetWidth+1+"px";if(img.offsetWidth+
1)img.style.width=origWidth}};pf.getSet=function(img){var i,set,supportsType;var match=false;var sets=img[pf.ns].sets;for(i=0;i<sets.length&&!match;i++){set=sets[i];if(!set.srcset||!pf.matchesMedia(set.media)||!(supportsType=pf.supportsType(set.type)))continue;if(supportsType==="pending")set=supportsType;match=set;break}return match};pf.parseSets=function(element,parent,options){var srcsetAttribute,imageSet,isWDescripor,srcsetParsed;var hasPicture=parent&&parent.nodeName.toUpperCase()==="PICTURE";
var imageData=element[pf.ns];if(imageData.src===undefined||options.src){imageData.src=getImgAttr.call(element,"src");if(imageData.src)setImgAttr.call(element,srcAttr,imageData.src);else removeImgAttr.call(element,srcAttr)}if(imageData.srcset===undefined||options.srcset||!pf.supSrcset||element.srcset){srcsetAttribute=getImgAttr.call(element,"srcset");imageData.srcset=srcsetAttribute;srcsetParsed=true}imageData.sets=[];if(hasPicture){imageData.pic=true;getAllSourceElements(parent,imageData.sets)}if(imageData.srcset){imageSet=
{srcset:imageData.srcset,sizes:getImgAttr.call(element,"sizes")};imageData.sets.push(imageSet);isWDescripor=(alwaysCheckWDescriptor||imageData.src)&&regWDesc.test(imageData.srcset||"");if(!isWDescripor&&imageData.src&&!getCandidateForSrc(imageData.src,imageSet)&&!imageSet.has1x){imageSet.srcset+=", "+imageData.src;imageSet.cands.push({url:imageData.src,d:1,set:imageSet})}}else if(imageData.src)imageData.sets.push({srcset:imageData.src,sizes:null});imageData.curCan=null;imageData.curSrc=undefined;
imageData.supported=!(hasPicture||imageSet&&!pf.supSrcset||isWDescripor&&!pf.supSizes);if(srcsetParsed&&pf.supSrcset&&!imageData.supported)if(srcsetAttribute){setImgAttr.call(element,srcsetAttr,srcsetAttribute);element.srcset=""}else removeImgAttr.call(element,srcsetAttr);if(imageData.supported&&!imageData.srcset&&(!imageData.src&&element.src||element.src!==pf.makeUrl(imageData.src)))if(imageData.src===null)element.removeAttribute("src");else element.src=imageData.src;imageData.parsed=true};pf.fillImg=
function(element,options){var imageData;var extreme=options.reselect||options.reevaluate;if(!element[pf.ns])element[pf.ns]={};imageData=element[pf.ns];if(!extreme&&imageData.evaled===evalId)return;if(!imageData.parsed||options.reevaluate)pf.parseSets(element,element.parentNode,options);if(!imageData.supported)applyBestCandidate(element);else imageData.evaled=evalId};pf.setupRun=function(){if(!alreadyRun||isVwDirty||DPR!==window.devicePixelRatio)updateMetrics()};if(pf.supPicture){picturefill=noop;
pf.fillImg=noop}else(function(){var isDomReady;var regReady=window.attachEvent?/d$|^c/:/d$|^c|^i/;var run=function(){var readyState=document.readyState||"";timerId=setTimeout(run,readyState==="loading"?200:999);if(document.body){pf.fillImgs();isDomReady=isDomReady||regReady.test(readyState);if(isDomReady)clearTimeout(timerId)}};var timerId=setTimeout(run,document.body?9:99);var debounce=function(func,wait){var timeout,timestamp;var later=function(){var last=new Date-timestamp;if(last<wait)timeout=
setTimeout(later,wait-last);else{timeout=null;func()}};return function(){timestamp=new Date;if(!timeout)timeout=setTimeout(later,wait)}};var lastClientWidth=docElem.clientHeight;var onResize=function(){isVwDirty=Math.max(window.innerWidth||0,docElem.clientWidth)!==units.width||docElem.clientHeight!==lastClientWidth;lastClientWidth=docElem.clientHeight;if(isVwDirty)pf.fillImgs()};on(window,"resize",debounce(onResize,99));on(document,"readystatechange",run)})();pf.picturefill=picturefill;pf.fillImgs=
picturefill;pf.teardownRun=noop;picturefill._=pf;window.picturefillCFG={pf:pf,push:function(args){var name=args.shift();if(typeof pf[name]==="function")pf[name].apply(pf,args);else{cfg[name]=args[0];if(alreadyRun)pf.fillImgs({reselect:true})}}};while(setOptions&&setOptions.length)window.picturefillCFG.push(setOptions.shift());window.picturefill=picturefill;if(typeof module==="object"&&typeof module.exports==="object")module.exports=picturefill;else if(typeof define==="function"&&define.amd)define("picturefill",
function(){return picturefill});if(!pf.supPicture)types["image/webp"]=detectTypeSupport("image/webp","data:image/webp;base64,UklGRkoAAABXRUJQVlA4WAoAAAAQAAAAAAAAAAAAQUxQSAwAAAABBxAR/Q9ERP8DAABWUDggGAAAADABAJ0BKgEAAQADADQlpAADcAD++/1QAA\x3d\x3d")})(window,document);function cq5forms_isArray(obj){if(Array.isArray)return Array.isArray(obj);else return Object.prototype.toString.call(obj)==="[object Array]"}
function cq5forms_isNodeList(obj){var prototypeName=Object.prototype.toString.call(obj);return typeof obj==="object"&&/^\[object (HTMLCollection|NodeList|RadioNodeList)\]$/.test(prototypeName)&&typeof obj.length==="number"&&(obj.length===0||typeof obj[0]==="object"&&obj[0].nodeType>0)}
function cq5forms_showMsg(fid,field,msg,index){var f=document.forms[fid].elements[field];alert(msg);if(cq5forms_isNodeList(f))f=Array.prototype.slice.call(f);if(cq5forms_isArray(f)){if(!index)index=0;f[index].focus()}else f.focus()}
function cq5forms_isEmpty(obj){if(obj===undefined)return false;var empty=true;if(cq5forms_isNodeList(obj))obj=Array.prototype.slice.call(obj);if(cq5forms_isArray(obj))for(i=0;i<obj.length;i++)if(obj[i].type=="radio"||obj[i].type=="checkbox"){if(obj[i].checked)empty=false}else if(obj[i].localName=="option"){if(obj[i].selected)empty=false}else{if(obj[i].value.length>0)empty=false}else if(obj.type=="radio"||obj.type=="checkbox"){if(obj.checked)empty=false}else if(obj.value.length>0)empty=false;return empty}
function cq5forms_regcheck(obj,pattern){var result=false;var t=pattern.exec(obj);if(t){var len=obj.length;var pattlen=t[0].length;result=pattlen==len}return result}function cq5forms_multiResourceChange(evt,name,force){if(!force){if(!evt)evt=window.event;if(evt.keyCode<48&&evt.keyCode!=8&&evt.keyCode!=46)return}try{document.getElementById(name).checked=true}catch(e){}}
$(document).on("click",".btn-mobile-prodlistadd",function(){var $button=$(this);var $row=$button.parents("tr");var $qty=$row.find("input.span1").val();var qty=parseInt($qty);var $sku=$row.find('input[name*\x3d"sku"]').val();if(qty>=1){var product={};product.sku=$sku;product.qty=qty;miniCart.addProductsToCart([product])}});
$(document).ready(function(){if($(".leftnav-standard").length>0||$(".leftnav-autopopulating").length>0||$(".leftnav-manual").length>0){$("#link-leftnav-toggle-container").show();$(".link-leftnav-toggle").on("click",function(event){event.preventDefault();var seeCTA=showHideText.seeRelatedText;var hideCTA=showHideText.hideRelatedText;var leftnavToggleText=$(this).text()==seeCTA?hideCTA:seeCTA;$(this).text(leftnavToggleText);$(".container-leftnav").toggleClass("in")});$(".item-header").on("click",function(event){event.preventDefault();
var $itemHeader=$(this);var $itemIcon=$itemHeader.find(".item-icon");var $itemContent=$itemHeader.siblings();$itemContent.toggleClass("in");$itemIcon.toggleClass("icon-plus icon-minus")})}});function urlParams(name){name=name.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");var regexS="[\\?\x26]"+name+"\x3d([^\x26#]*)";var regex=new RegExp(regexS);var results=regex.exec(window.location.search);if(results==null)return"";else return decodeURIComponent(results[1].replace(/\+/g," "))}
!function($){$(function(){var param1=urlParams("param1");var param2=urlParams("param2");$("#imageGalleryKeyword").val(param1);$("#imageGalleryCategory").val(param2);$("#imageGalleryCategory").on("change",function(){$("#imageGalleryForm").submit()});$("#imageGalleryForm").on("submit",function(){getImageGalleryValues()});function getImageGalleryValues(){var categoryVal=$("#imageGalleryCategory").val(),keywordVal=$("#imageGalleryKeyword").val();$('input[name\x3d"param1"]').val(keywordVal);$('input[name\x3d"param2"]').val(categoryVal)}
})}(window.$j);(function($){$.fn.filmstrip=function(){return this.each(function(){var $this=$(this),thumbnails=$this.find(".thumbnail"),filmstripInner=$this.find(".filmstrip-inner"),filmstripWidth=$this.width(),itemCount=3,i=0;for(i=0;i<thumbnails.length;i+=itemCount)thumbnails.slice(i,i+itemCount).wrapAll('\x3cdiv class\x3d"item"\x3e\x3c/div\x3e');$this.find(".item:first").addClass("active");filmstripInner.toggleClass("hide show")})}})($j);var pageNo=1;var filteredCall=false;var noOfRecord=0;
var ajaxRunningStatus=false;var paging=0;var jsonResultSet;var pageNumber;var eventSelected="";var appSelected="";var startDateSelected="";var endDateSelected="";var countrySelected="";var preSelectedFacets=[];var status="";var countryCode="";var clearHTML=true;var previousPage;var showMessage="";var allEventOptionTxt="";var allAppOptionTxt="";var allCountryOptionTxt="";function setJsValues(recordsperpage,isoCode){noOfRecord=recordsperpage;countryCode=isoCode}
function eventPaginationHTMLTemplate(obj,appendToId){var $eventPagination=$("#"+appendToId);$eventPagination.empty();if(obj.hasOwnProperty("total")){var $divPagination=$("\x3cdiv class\x3d'pagination'/\x3e");var currentOffset=noOfRecord*(pageNo-1);var maxIteration=parseInt(currentOffset)+parseInt(noOfRecord);var total=obj.total;if(maxIteration<total)var $viewMore=$('\x3ca href\x3d"javascript:void(0);" onclick\x3d"viewMoreEvents();"/\x3e').html("View More").appendTo($divPagination).appendTo($eventPagination)}}
function viewMoreEvents(){pageNo=pageNo+1;clearHTML=false;eventListHTMLTemplate(jsonResultSet,"eventListContainer");eventPaginationHTMLTemplate(jsonResultSet,"eventPagination");return false}
function eventListHTMLTemplate(obj,appendToId){jsonResultSet=obj;var $list;if(clearHTML){$("#eventListContainer").empty();$list=$("\x3cul id\x3d'eventUL'/\x3e").appendTo($("#eventListContainer"))}else $list=$("#eventListContainer ul#eventUL");if(obj.hasOwnProperty("events")){var eventList=obj.events;var currentOffset=noOfRecord*(pageNo-1);var maxIteration=parseInt(currentOffset)+parseInt(noOfRecord);if(obj.total<maxIteration)maxIteration=obj.total;for(var i=currentOffset;i<maxIteration;i++){var event=
eventList[i];var $listItem=$("\x3cli class\x3d'eventContainer'/\x3e");var $figure=$("\x3cfigure class\x3d'eventInfo'/\x3e");var $thumbnail=$("\x3cimg class\x3d'eventThummb'/\x3e");var $eventLink=$("\x3ca /\x3e").attr("href",event.ePath);if(event.hasOwnProperty("eThumbnail")&&event.eThumbnail.length>0){var thumbnailprop=event.eThumbnail;if(thumbnailprop!=null&&thumbnailprop!="")if(thumbnailprop.length>0)$eventLink.append($thumbnail.attr("src",event.eThumbnail)).appendTo($figure)}else{var defaultThumbnail=
"/etc/designs/komodo/clientlibs/sharedstatic/img/events-thumb.jpeg";$eventLink.append($thumbnail.attr("src",defaultThumbnail)).appendTo($figure)}var $figcaption=$("\x3cfigcaption class\x3d'eventDtl'/\x3e");if(event.hasOwnProperty("eType")){var tempetype=event.eType;if(tempetype!=null&&tempetype!="")if(tempetype.length>0)var $eventType=$("\x3cspan class\x3d'eventType label label-info pull-right'/\x3e").html(event.eType).appendTo($figcaption)}if(event.hasOwnProperty("ePath")&&event.hasOwnProperty("eTitle")){{var $eventTitleLink=
$('\x3ca class\x3d"link-action"/\x3e').attr("href",event.ePath).attr("alt",event.eTitle).attr("title",event.eTitle).html(event.eTitle);var $eventTitle=$("\x3ch3 class\x3d'eventTitle'/\x3e").append($eventTitleLink).appendTo($figcaption)}}if(event.hasOwnProperty("eSchedule")){var schedule=event.eSchedule;var startDate="";if(schedule.hasOwnProperty("eStartDate"))startDate=schedule.eStartDate;var endDate="";if(schedule.hasOwnProperty("eEndDate"))endDate=schedule.eEndDate;if(startDate.length>0&&endDate.length>
0)var $eventSchedule=$("\x3cspan class\x3d'eventSchedule'/\x3e").html(startDate+" - "+endDate).appendTo($figcaption);if(startDate.length>0&&endDate.length==0)var $eventSchedule=$("\x3cspan class\x3d'eventSchedule'/\x3e").html(startDate).appendTo($figcaption)}if(event.hasOwnProperty("props")){var propArray=event.props;if(propArray!=null&&propArray!=""){var $eventPropBlock=$("\x3cspan class\x3d'eventProps' style\x3d'inline-block'/\x3e");for(var j=0;j<propArray.length;j++){var prop=propArray[j];var $eventProp=
$('\x3cspan class\x3d"prop"/\x3e').html("\x3cstrong\x3e"+prop.name+": "+(prop.vtype=="cur"?"$":"")+prop.value+"\x3c/strong\x3e").appendTo($eventPropBlock)}$eventPropBlock.appendTo($figcaption)}}if(event.hasOwnProperty("eVenue"))var $eventHeading=$("\x3cspan/\x3e").addClass("eventLocation").html(event.eVenue).appendTo($figcaption);if(event.hasOwnProperty("eDesc")){var description=event.eDesc;var $eventDesc=$("\x3cspan class\x3d'eventDescription'/\x3e").append(description).appendTo($figcaption)}$figcaption.appendTo($figure);
$figure.appendTo($listItem);$list.append($listItem)}}else{$noEventFound=$('\x3cdiv class\x3d"noResultFound"/\x3e');$noEventFound.html(showMessage);$("#eventListContainer").append($noEventFound)}}
function loadEvents(path,eventType,appType,startDate,endDate,country,searchTerm,pageNo,noOfRecord,dispMessage,preSelectedFacets,eventsOptiontxt,appOptiontxt,countryOptiontxt){if(null==country)country="";var preselectedFacetsString="";if(preSelectedFacets!=null&&preSelectedFacets.length>0)preselectedFacetsString=preSelectedFacets.toString();showMessage=dispMessage;allEventOptionTxt=eventsOptiontxt;allAppOptionTxt=appOptiontxt;allCountryOptionTxt=countryOptiontxt;if(!ajaxRunningStatus){ajaxRunningStatus=
true;startLoadingAnimation();console.log("***LoadEvents eventType \x3d"+eventType);console.log("***LoadEvent sappType \x3d"+appType);console.log("***LoadEvents startDate \x3d"+startDate);console.log("**LoadEvents endDate \x3d"+endDate);console.log("**LoadEvents country \x3d"+country);console.log("**LoadEvents searchTerm \x3d"+searchTerm);$.ajax({url:"/bin/eventDataRecordMaster.html",contentType:"application/json;charset\x3dutf-8",data:{"eventType":eventType,"appType":appType,"startDate":startDate,
"endDate":endDate,"country":country,"searchTerm":encodeURIComponent(searchTerm),"pageNo":pageNo,"freshCall":filteredCall,"noOfRecord":noOfRecord,"path":path,"preSelectedFacets":preselectedFacetsString},type:"GET",success:function(response){ajaxRunningStatus=false;processEventList(response);$("#eventListLoader").hide()},error:function(xhr){ajaxRunningStatus=false}})}}
function startLoadingAnimation(){var progressHtml='\x3cul id\x3d"progress"\x3e'+'\x3cli\x3e\x3cdiv id\x3d"layer1" class\x3d"ball"\x3e\x3c/div\x3e\x3cdiv id\x3d"layer7" class\x3d"pulse"\x3e\x3c/div\x3e\x3c/li\x3e'+'\x3cli\x3e\x3cdiv id\x3d"layer2" class\x3d"ball"\x3e\x3c/div\x3e\x3cdiv id\x3d"layer8" class\x3d"pulse"\x3e\x3c/div\x3e\x3c/li\x3e'+'\x3cli\x3e\x3cdiv id\x3d"layer3" class\x3d"ball"\x3e\x3c/div\x3e\x3cdiv id\x3d"layer9" class\x3d"pulse"\x3e\x3c/div\x3e\x3c/li\x3e'+'\x3cli\x3e\x3cdiv id\x3d"layer4" class\x3d"ball"\x3e\x3c/div\x3e\x3cdiv id\x3d"layer10" class\x3d"pulse"\x3e\x3c/div\x3e\x3c/li\x3e'+
'\x3cli\x3e\x3cdiv id\x3d"layer5" class\x3d"ball"\x3e\x3c/div\x3e\x3cdiv id\x3d"layer11" class\x3d"pulse"\x3e\x3c/div\x3e\x3c/li\x3e'+"\x3c/ul\x3e";$("#eventListLoader").html(progressHtml)}
function bindFilterChange(filterClass){var filterArray=$("."+filterClass);if(filterArray&&filterArray.length>0)filterArray.each(function(idx){$(this).change(function(){pageNo=1;clearHTML=true;jsonResultSet={};loadEventsFilterData()})});$j("#searchfilter").keypress(function(e){if(e.which===13){pageNo=1;clearHTML=true;jsonResultSet={};loadEventsFilterData()}});$j('a[href\x3d"#red-icon-search-events"]').click(function(){pageNo=1;clearHTML=true;jsonResultSet={};loadEventsFilterData()});var country=$("#countryfilter");
country.change(function(){pageNo=1;clearHTML=true;jsonResultSet={};var apptype=$("#apptypeselect");if(apptype.length)apptype.val("");var eventType=$("#eventtypeselect");if(eventType.length)eventType.val("");loadEventsFilterData()});$j("#startdatefilter").datepicker().on("change",function(){pageNo=1;clearHTML=true;jsonResultSet={};$(".datepicker").hide();loadEventsFilterData()});$j("#enddatefilter").datepicker().on("change",function(){pageNo=1;clearHTML=true;jsonResultSet={};$(".datepicker").hide();
loadEventsFilterData()})}function paginationLoad(pageNumber){pageNo=pageNumber;loadEventsFilterData()}
function loadEventsFilterData(){var event=$("#eventtypeselect");var eventType=event.length>0&&event.val()!=""?event.val():eventSelected;var application=$("#apptypeselect");var applicationValue=application.length>0&&application.val()!=""?application.val():appSelected;var startdate=$("#startdatefilter");var startdateValue=startdate.length>0?startdate.val():startDateSelected;var enddate=$("#enddatefilter");var enddateValue=enddate.length>0?enddate.val():endDateSelected;var country=$("#countryfilter");
var countryValue=country.length>0?country.val():countrySelected;var search=$("#searchfilter");var searchValue=search.length>0?search.val():"";var path=$("#searchEventUnderPath");var pathValue=path.length>0?path.val():"";var message=showMessage;var allEventsTxt=allEventOptionTxt;var allAppTxt=allAppOptionTxt;var allCountryTxt=allCountryOptionTxt;loadEvents(pathValue,eventType,applicationValue,startdateValue,enddateValue,countryValue,searchValue,pageNo,noOfRecord,message,preSelectedFacets,allEventsTxt,
allAppTxt,allCountryTxt)}function processEventList(response){processFilters(response);bindFilterChange("eventFilter");eventListHTMLTemplate(response,"eventListContainer");eventPaginationHTMLTemplate(response,"eventPagination")}
function processFilters(response){if(response&&response.hasOwnProperty("facets")){var facets=response.facets;var eventSelected="";var appSelected="";var countrySelected="";if(response.hasOwnProperty("eventSelected"))eventSelected=response.eventSelected;if(response.hasOwnProperty("appSelected"))appSelected=response.appSelected;if(response.hasOwnProperty("countrySelected"))countrySelected=response.countrySelected;if(facets&&facets.hasOwnProperty("appType")){var appType=facets.appType;var $apptypeselect=
$("#apptypeselect");var apptypeMaster=[];if($apptypeselect.length){$apptypeselect.empty();$apptypeselect.append($("\x3coption/\x3e").text(allAppOptionTxt).attr("value",""));$.each(appType,function(key,value){apptypeMaster.push([key,value])});apptypeMaster.sort(function(a,b){a=a[1];b=b[1];return a<b?-1:a>b?1:0});for(var i=0;i<apptypeMaster.length;i++){var key=apptypeMaster[i][0];var value=apptypeMaster[i][1];if(appSelected==value)$apptypeselect.append($("\x3coption selected/\x3e").text(key).attr("value",
value));else $apptypeselect.append($("\x3coption/\x3e").text(key).attr("value",value))}}}if(facets&&facets.hasOwnProperty("eventType")){var eventType=facets.eventType;var $eventtypeselect=$("#eventtypeselect");var eventypeMaster=[];if($eventtypeselect.length){$eventtypeselect.empty();$eventtypeselect.append($("\x3coption/\x3e").text(allEventOptionTxt).attr("value",""));$.each(eventType,function(key,value){eventypeMaster.push([key,value])});eventypeMaster.sort(function(a,b){a=a[1];b=b[1];return a<
b?-1:a>b?1:0});for(var i=0;i<eventypeMaster.length;i++){var key=eventypeMaster[i][0];var value=eventypeMaster[i][1];if(eventSelected==value)$eventtypeselect.append($("\x3coption selected/\x3e").text(key).attr("value",value));else $eventtypeselect.append($("\x3coption/\x3e").text(key).attr("value",value))}}}var selectedCountryAvailable=false;if(facets&&facets.hasOwnProperty("country")){var country=facets.country;var $countryfilter=$("#countryfilter");var countryMaster=[];console.log("countryFilter length \x3d "+
$countryfilter.length);if($countryfilter.length){$countryfilter.empty();$countryfilter.append($("\x3coption/\x3e").text(allCountryOptionTxt).attr("value",""));$.each(country,function(key,value){if(key!="")countryMaster.push([value,key])});if(!selectedCountryAvailable&&countrySelected.length>0){var countryName="";var countryItem=country[countrySelected];if(typeof countryItem!="undefined")countryName=countryItem;if(countryName!=countryItem)countryMaster.push([countryName,countrySelected])}countryMaster.sort(function(a,
b){a=a[0];b=b[0];return a<b?-1:a>b?1:0});for(var i=0;i<countryMaster.length;i++){var key=countryMaster[i][0];var value=countryMaster[i][1];if(countrySelected==value)$countryfilter.append($("\x3coption selected/\x3e").text(key).attr("value",value));else $countryfilter.append($("\x3coption/\x3e").text(key).attr("value",value))}}}filteredCall=true}}
(function(window,document){var version="3.7.3";var options=window.html5||{};var reSkip=/^<|^(?:button|map|select|textarea|object|iframe|option|optgroup)$/i;var saveClones=/^(?:a|b|code|div|fieldset|h1|h2|h3|h4|h5|h6|i|label|li|ol|p|q|span|strong|style|table|tbody|td|th|tr|ul)$/i;var supportsHtml5Styles;var expando="_html5shiv";var expanID=0;var expandoData={};var supportsUnknownElements;(function(){try{var a=document.createElement("a");a.innerHTML="\x3cxyz\x3e\x3c/xyz\x3e";supportsHtml5Styles="hidden"in
a;supportsUnknownElements=a.childNodes.length==1||function(){document.createElement("a");var frag=document.createDocumentFragment();return typeof frag.cloneNode=="undefined"||typeof frag.createDocumentFragment=="undefined"||typeof frag.createElement=="undefined"}()}catch(e){supportsHtml5Styles=true;supportsUnknownElements=true}})();function addStyleSheet(ownerDocument,cssText){var p=ownerDocument.createElement("p"),parent=ownerDocument.getElementsByTagName("head")[0]||ownerDocument.documentElement;
p.innerHTML="x\x3cstyle\x3e"+cssText+"\x3c/style\x3e";return parent.insertBefore(p.lastChild,parent.firstChild)}function getElements(){var elements=html5.elements;return typeof elements=="string"?elements.split(" "):elements}function addElements(newElements,ownerDocument){var elements=html5.elements;if(typeof elements!="string")elements=elements.join(" ");if(typeof newElements!="string")newElements=newElements.join(" ");html5.elements=elements+" "+newElements;shivDocument(ownerDocument)}function getExpandoData(ownerDocument){var data=
expandoData[ownerDocument[expando]];if(!data){data={};expanID++;ownerDocument[expando]=expanID;expandoData[expanID]=data}return data}function createElement(nodeName,ownerDocument,data){if(!ownerDocument)ownerDocument=document;if(supportsUnknownElements)return ownerDocument.createElement(nodeName);if(!data)data=getExpandoData(ownerDocument);var node;if(data.cache[nodeName])node=data.cache[nodeName].cloneNode();else if(saveClones.test(nodeName))node=(data.cache[nodeName]=data.createElem(nodeName)).cloneNode();
else node=data.createElem(nodeName);return node.canHaveChildren&&!reSkip.test(nodeName)&&!node.tagUrn?data.frag.appendChild(node):node}function createDocumentFragment(ownerDocument,data){if(!ownerDocument)ownerDocument=document;if(supportsUnknownElements)return ownerDocument.createDocumentFragment();data=data||getExpandoData(ownerDocument);var clone=data.frag.cloneNode(),i=0,elems=getElements(),l=elems.length;for(;i<l;i++)clone.createElement(elems[i]);return clone}function shivMethods(ownerDocument,
data){if(!data.cache){data.cache={};data.createElem=ownerDocument.createElement;data.createFrag=ownerDocument.createDocumentFragment;data.frag=data.createFrag()}ownerDocument.createElement=function(nodeName){if(!html5.shivMethods)return data.createElem(nodeName);return createElement(nodeName,ownerDocument,data)};ownerDocument.createDocumentFragment=Function("h,f","return function(){"+"var n\x3df.cloneNode(),c\x3dn.createElement;"+"h.shivMethods\x26\x26("+getElements().join().replace(/[\w\-:]+/g,function(nodeName){data.createElem(nodeName);
data.frag.createElement(nodeName);return'c("'+nodeName+'")'})+");return n}")(html5,data.frag)}function shivDocument(ownerDocument){if(!ownerDocument)ownerDocument=document;var data=getExpandoData(ownerDocument);if(html5.shivCSS&&!supportsHtml5Styles&&!data.hasCSS)data.hasCSS=!!addStyleSheet(ownerDocument,"article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}"+"mark{background:#FF0;color:#000}"+"template{display:none}");if(!supportsUnknownElements)shivMethods(ownerDocument,
data);return ownerDocument}var html5={"elements":options.elements||"abbr article aside audio bdi canvas data datalist details dialog figcaption figure footer header hgroup main mark meter nav output picture progress section summary template time video","version":version,"shivCSS":options.shivCSS!==false,"supportsUnknownElements":supportsUnknownElements,"shivMethods":options.shivMethods!==false,"type":"default","shivDocument":shivDocument,createElement:createElement,createDocumentFragment:createDocumentFragment,
addElements:addElements};window.html5=html5;shivDocument(document);if(typeof module=="object"&&module.exports)module.exports=html5})(typeof window!=="undefined"?window:this,document);
function LineItem(sku,quantity,description,price,size,assayID,assayName,purity,scale,ratePlanId,ratePlanName,productRateChargeId,baseLineKey,baseLineSku,billingPeriod,lineNo,parentLineNo){this.SKU=sku;this.quantity=quantity;this.name=description;this.unitPrice=price;this.size=size;this.assayID=assayID;this.assayName=assayName;this.purity=purity;this.scale=scale;this.ratePlanId=ratePlanId;this.ratePlanName=ratePlanName;this.productRateChargeId=productRateChargeId;this.baseLineKey=baseLineKey;this.baseLineSku=
baseLineSku;this.billingPeriod=billingPeriod;if(parentLineNo)this.parentLineNo=parentLineNo;else this.parentLineNo="";if(lineNo)this.lineNo=lineNo;else this.lineNo="";for(var i in this)if(!this[i]||this[i]=="undefined"||this[i]==undefined)this[i]=""}
var productListCartHandler=function($this){$this.addToCart=function(formId){if(typeof miniCart!="undefined"){$this.registerMiniCartCallback();$this.getFormValues(formId);miniCart.addToCart(formId)}};$this.addLineItem=function(sku,quantity,description,price,size,assayID,assayName,purity,scale,ratePlanId,ratePlanName,productRateChargeId,baseLineKey,baseLineSku,billingPeriod,lineNo,parentLineNo){var lineItem=new LineItem(sku,quantity,description,price,size,assayID,assayName,purity,scale,ratePlanId,ratePlanName,
productRateChargeId,baseLineKey,baseLineSku,billingPeriod,lineNo,parentLineNo);return lineItem};$this.getFormValues=function(cartForm,additionalOmniParameters){var lineItems=[];var form="productForm";if(cartForm!=undefined&&cartForm!="")form=cartForm;var hasQuantity=false;var addToCartSkus=0;var addToCartErrorSkus=0;var quantity=0;var sku,price,description,size;var assayID,assayName,purity,scale;var i;var productRatePlanId;var productRatePlanName="";var productRateChargeId;var baseLineKey;var baseLineSku=
"";var billingPeriod="";$("#"+form+" input").each(function(x){if(nameExists(this,"qty")){i=0;if(this.value>0&&this.value%1==0){quantity=this.value;addToCartSkus++;hasQuantity=true}else if(this.value!="")addToCartErrorSkus++}if(hasQuantity==true){i++;sku=nameExists(this,"sku")?this.value:sku;size=nameExists(this,"size")?this.value:size;description=nameExists(this,"productname")?this.value:description;price=nameExists(this,"price")?this.value:price;assayID=nameExists(this,"assayID")?this.value:assayID;
assayName=nameExists(this,"assayName")?this.value:assayName;purity=nameExists(this,"purity")?this.value:purity;scale=nameExists(this,"scale")?this.value:scale;if(i%10==9&&i!=1){if(!isValidQuantity(quantity)&&quantity!="")errorSkus+=sku+",";else if(quantity!=""){var LineItem=productListCartHandler.addLineItem(sku,quantity,description,price,size,assayID,assayName,purity,scale,"","","","","","");lineItems.push(LineItem)}quantity="",sku="",price="",description="",size="";assayID="",assayName="",purity=
"",scale="";hasQuantity=false}}});var lineNo=0;var parentLineNo=1;var hasSubscription=false;$("#"+form+" .ddsubscription , #"+form+" .cbsubscription").each(function(index,element){quantity="1";hasSubscription=true;if($(this).hasClass("cbsubscription")&&$(this).is(":checked")&&nameExists(this,"addOnProductGroup")){lineNo++;productRatePlanId=$(this).attr("rate-plan-id");productRateChargeId=$(this).attr("rate-plan-charge-id");productRatePlanName=$(this).attr("rate-plan-name");billingPeriod=$(this).attr("rate-plan-billing-period");
baseLineSku=$(this).attr("base-sku-name");sku=$(this).attr("sku-name");var LineItem=productListCartHandler.addLineItem(sku,quantity,description,price,size,assayID,assayName,purity,scale,productRatePlanId,productRatePlanName,productRateChargeId,baseLineKey,baseLineSku,billingPeriod,lineNo,parentLineNo);lineItems.push(LineItem)}else if($(this).hasClass("ddsubscription")&&$("option:selected",this).length>0){lineNo++;productRatePlanId=nameExists(this,"Subscription")?$("option:selected",this).attr("rate-plan-id"):
productRatePlanId;productRateChargeId=nameExists(this,"Subscription")?$("option:selected",this).attr("rate-plan-charge-id"):productRateChargeId;productRatePlanName=nameExists(this,"Subscription")?$("option:selected",this).attr("rate-plan-name"):productRatePlanName;billingPeriod=nameExists(this,"Subscription")?$("option:selected",this).attr("rate-plan-billing-period"):billingPeriod;sku=$(this).attr("sku-name");var LineItem=productListCartHandler.addLineItem(sku,quantity,description,price,size,assayID,
assayName,purity,scale,productRatePlanId,productRatePlanName,productRateChargeId,baseLineKey,baseLineSku,billingPeriod,lineNo);lineItems.push(LineItem)}quantity="",sku="",price="",description="",size="";assayID="",assayName="",purity="",scale="",productRatePlanId="",productRatePlanName="",productRateChargeId="",billingPeriod=""});$this.lineItems=lineItems;console.log("FINISHED recording productList lineItems with a count of ["+$this.lineItems.length+"]");return lineItems};$this.handleMiniCartCallback=
function(){console.log("RECEIVED miniCart callback");var productData=[];for(var i in $this.lineItems){var cartItem={addMethod:"cq-product-list",catalogNumber:$this.lineItems[i].SKU,quantity:$this.lineItems[i].quantity,title:$this.lineItems[i].name,price:$this.lineItems[i].unitPrice,categoryId:"",categoryName:"",lineName:"",designId:"",uom:""};productData.push(cartItem)}if(productData.length)try{console.log("DISPATCHING digitalData [cartAdd] event");document.dispatchEvent(new CustomEvent("cartAdd",
{detail:{products:productData}}))}catch(e){console.log(e)}this.lineItems=[]};$this.registerMiniCartCallbackComplete=false;$this.registerMiniCartCallback=function(){if($this.registerMiniCartCallbackComplete)return;if(typeof miniCart!="undefined"){miniCart.setAddToCartSuccessCallback(productListCartHandler.handleMiniCartCallback);$this.registerMiniCartCallbackComplete=true;console.log("registerMiniCartCallbackComplete COMPLETE")}};return $this}(productListCartHandler||{});
function reorderColumnControl(){var colctrls=$("div[comp-order]");$.each(colctrls,function(index,item){var colctrlNo=index+1;var noRow=0;var child=$(item).children();var colCtrlContainerClass=$(this).attr("class");var compOrder=$(this).attr("comp-order");var row=$("\x3cdiv class\x3d'"+colCtrlContainerClass+"'\x3e\x3c/div\x3e");$.each(child,function(index,childitem){var colclass=$(childitem).attr("class");var colelement=$("\x3cdiv class\x3d'"+colclass+"'\x3e\x26nbsp;\x3c/div\x3e");row=$(row).append($(colelement));
if(noRow<$(childitem).find("div[comp-id]").length)noRow=$(childitem).find("div[comp-id]").length});if(compOrder=="bycol")noRow=1;for(var i=1;i<=noRow;i++){row=$(row).attr("colctrl-id",colctrlNo+"-"+i);$(row).clone().insertBefore($(item))}var columnSelector=colCtrlContainerClass.replace(" ",".");$.each(child,function(index,childitem){var colno=index;var componentSelector="div[container-id\x3d"+colCtrlContainerClass.replace("parsys_column ","")+"][comp-id]";var comps=$(childitem).find(componentSelector);
$.each(comps,function(compindex,compitem){var compid=$(compitem).attr("comp-id");var rowno=compid.substring(1,compid.length);if(compOrder=="bycol")rowno=1;var destination=$("div[colctrl-id\x3d'"+colctrlNo+"-"+rowno+"'] div."+columnSelector+"-c"+colno);if(destination.size()==1){destination=destination[0];$("script",$(compitem)).remove();var source=$(compitem);try{if(rowno>=compindex+1)$(destination).html(source);else $(destination).append(source)}catch(err){console.log("error moving component");console.log(source);
console.log(err)}}})});var form=$("form",item);if(form){form.insertBefore($(item));var formContainer=$(".form",form);for(var i=1;i<=noRow;i++){row=$(row).attr("colctrl-id",colctrlNo+"-"+i);$("div[colctrl-id\x3d'"+colctrlNo+"-"+i+"']").appendTo($(formContainer))}}})}$(document).ready(function(){var reorder=true;if(CQ.WCM.edit)if(CQ.WCM.isEditMode(true)||CQ.WCM.isDesignMode(true))reorder=false;if(reorder)reorderColumnControl()});
$(document).ready(function(){var featuredcategories=$(".featuredcategoriescontainer");$.each(featuredcategories,function(index,item){var colcount=$(item).find("input[name\x3dcolcount]").val();var featuredcategory=$(item).find(".featuredcategory");$.each(featuredcategory,function(innerindex,eachcategory){if(innerindex>=colcount&&innerindex%colcount==0)$(eachcategory).css("clear","left")})})});
(function($){$.fn.showhide=function(settings){var o=$.extend({},$.fn.showhide.defaults,settings);return this.each(function(){var blockClass=this.className,toggleButton='\x3ca href\x3d"#" class\x3d"'+o.toggleClass+" "+o.hiddenClass+'"\x3e'+o.moreText+"\x3c/a\x3e";$("."+blockClass).each(function(){$(this).after(toggleButton);$(this).hide()});$("."+o.toggleClass).toggle(function(){$(this).removeClass(o.hiddenClass).addClass(o.visibleClass).html(o.lessText).prev("."+blockClass).slideDown(100)},function(){$(this).removeClass(o.visibleClass).addClass(o.hiddenClass).html(o.moreText).prev("."+
blockClass).slideUp(100)});return false})};$.fn.showhide.defaults={toggleClass:"toggle-view",hiddenClass:"toggle-hidden",visibleClass:"toggle-visible",moreText:"View more",lessText:"View less"}})(jQuery);var countryInfo={"country":[{"CountryCode":"","CountryName":"","CountryFlag":"","CountryPhone":"\x26nbsp;","CountrySupportHours":"\x26nbsp;","CountryLanguages":""}]};
function CFC_popup(url,name,features){var defaultWidth=500;var defaultHeight=400;name=name.replace(" ","");if(url.indexOf("/")==0)url=""+url;if(features.indexOf("width")==-1)features+=",width\x3d"+defaultWidth;if(features.indexOf("height")==-1)features+=",height\x3d"+defaultHeight;var w=window.open(url,name,features);w.focus()}function getIEVersion(){var dataString=navigator.userAgent;var index=dataString.indexOf("MSIE");if(index==-1)return;return parseFloat(dataString.substring(index+5))}
function nextEmail(email,confirmation,currentHandle){$("#cluetip").width("258px");$("#ttEmailFormButton").width("125px");$("#cluetip-inner").load(email,function(){$("a.cluetip-close").click(function(){$("#cluetip-inner").empty();$("#cluetip").hide();return false});$("#ttEmailFormButton").bind("click",function(){var errorMsgTo="";var errorMsgFrom="";var bErrors=false;var emailRegEx=/^([a-zA-Z0-9_\.\-])+@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;var to=document.getElementById("ttEmailFormTo");var from=
document.getElementById("ttEmailFormFrom");var subject=document.getElementById("ttEmailFormSubject");var message=document.getElementById("ttEmailFormMessage");var bSendMsg=false;if(to.value==""){errorMsgTo="Please Provide Collegues Email \x3cbr /\x3e";bErrors=true}else if(emailRegEx.test(to.value)!=true){bErrors=true;errorMsgTo="Your collegues email address is not valid \x3cbr /\x3e"}if(from.value==""){errorMsgFrom="Please Provide Your Email \x3cbr /\x3e";bErrors=true}else if(emailRegEx.test(from.value)!=
true){bErrors=true;errorMsgFrom="Your email address is not valid"}if(bErrors==true){var errMsg=document.getElementById("errormsg");errMsg.innerHTML="The following errors occured \x3cbr /\x3e"+errorMsgTo+errorMsgFrom}else{var url=document.getElementById("ttEmailFormURL");url=url.value;$.ajax({type:"GET",url:url,async:true,data:"to\x3d"+to.value+"\x26from\x3d"+from.value+"\x26subject\x3d"+encodeURIComponent(subject.value)+"\x26message\x3d"+encodeURIComponent(message.value)+"\x26currentHandle\x3d"+encodeURIComponent(currentHandle)+
"\x26url\x3d"+url,success:function(data){$("#cluetip-inner").load(confirmation,function(){$("a.cluetip-close").click(function(){$("#cluetip-inner").empty();$("#cluetip").hide();return false})})},error:function(msg){$("#cluetip-inner").empty();$("#cluetip").hide();return false}})}return false})});var newLeft=parseInt($("#cluetip").css("left"))-153;if(document.getElementById("cluetip-head")==null)$("#cluetip").css("left",newLeft+"px");return false}
function nextTip(height,width,url){$("#cluetip").width(width+"px");$("#cluetip").height(height+"px");var newLeft=parseInt($("#cluetip").css("left"))-(width-100);$("#cluetip").css("left",newLeft+"px");$("#cluetip-inner").load(url,function(){$("a.cluetip-close").click(function(){$("#cluetip-inner").empty();$("#cluetip").hide();return false})});return false}function getCountryIcon(){return includesDomain+"/shared-static/images/icons/flags/"+countryInfo.country[0].CountryFlag}
function getCountryHeaderName(){return countryInfo.country[0].CountryName}function getCountryPhone(){return countryInfo.country[0].CountryPhone}function getCountrySupportHours(){return countryInfo.country[0].CountrySupportHours}function getCountryLanguages(){return countryInfo.country[0].CountryLanguages}function findValue(li){if(li==null)return alert("No match!");if(!!li.extra)var sValue=li.extra[0];else var sValue=li.selectValue}function selectItem(li){findValue(li)}
function formatItem(row){return row[0]}
$(document).ready(function(){$("a#slidein").click(function(){$("div#loginWrap").find("div#loginBox:hidden").slideDown("slow");$("div#loginExpand").hide();$("div#loginContract").show()});$("a#slideout").click(function(){$("div#loginWrap").find("div#loginBox:visible").slideUp("slow");$("div#loginContract").hide();$("div#loginExpand").show()});$("div#loginContract").hide();$("div#loginBox").hide();$("#contentQuickForm input").focus(function(){$(this).addClass("focused")}).blur(function(){$(this).removeClass("focused")});$("div#loginExpand").show();
$("span.selected ~ ul").show()});
$j(document).ready(function(){$j(".rte-table-cvc th, .rte-table-cvc td").hover(function(){var targetIndex=parseInt($j(this).index())+1;var elements=$j(this).parents("table");if(targetIndex>1){elements.find("td:nth-child("+targetIndex+")").css("background-color","#ebf2fa");elements.find("th:nth-child("+targetIndex+")").css("background-color","#ebf2fa")}},function(){var targetIndex=parseInt($j(this).index())+1;var elements=$j(this).parents("table");if(targetIndex>1){elements.find("td:nth-child("+targetIndex+
")").css("background-color","transparent");elements.find("th:nth-child("+targetIndex+")").css("background-color","transparent")}})});
var ResponsiveCQTables=function(){var freezeRow=function(table){$(table).tableHeadFixer();$(table).parent().addClass("table-row-frozen")};var freezeColumn=function(table){$(table).tableHeadFixer({"head":false,"left":1});$(table).parent().addClass("table-column-frozen")};var noWideScroll=function(table,isChecked){switch(isChecked){case "true":$(table).parent().removeClass("table-scroll-horizontal");break;case "false":$(table).parent().addClass("table-scroll-horizontal");break;default:return}};var maintainDesktopWidth=
function(table){$(table).parent().addClass("table-desktop-width")};var checkAttribute=function(table){var $table=$(table);if($table.attr("data_freeze_first_row"))freezeRow($table);else if($table.attr("data_freeze_first_col"))freezeColumn($table);else if($table.attr("data_no_wide_scroll"))noWideScroll($table,$table.attr("data_no_wide_scroll"));else maintainDesktopWidth($table)};return{check:function(element){checkAttribute(element)}}}();
$(function(){$(".table-component-wrapper table").each(function(){var $this=$(this);ResponsiveCQTables.check($this)})});$(document).ready(function(){if($(".seo").length>0){var jsonldScript=document.createElement("script");jsonldScript.type="application/ld+json";var events=[];$(".seo-eventdetailslistitem").each(function(){var eventitem=populateEventScript(this);events.push(eventitem)});jsonldScript.text=JSON.stringify(events);document.querySelector("head").appendChild(jsonldScript)}});
function populateEventScript(parentDiv){var eventValues={};eventValues["@context"]="http://schema.org";eventValues["@type"]="Event";var nameScriptValue=populateNameScript(parentDiv);var eventAttributes=[];$(".seo-event",parentDiv).each(function(){$(this).each(function(){var schemaType=$(this).attr("data-seo-schema");if(schemaType=="Event"){var seo_element_val=$(this).text().trim();seo_element_val=seo_element_val.replace(/[\r\n]+/g," ");eventValues[$(this).attr("data-seo-element")]=seo_element_val;
eventAttributes.push($(this).attr("data-seo-element"))}})});if($.inArray("name",eventAttributes)==-1)eventValues["name"]=populateNameScript(parentDiv);eventValues["location"]=populateLocationScript(parentDiv);var offers=populateOffersScript(parentDiv);if(offers&&offers.url)eventValues["offers"]=offers;var imageScriptValue=populateImageScript(parentDiv);if(imageScriptValue.length>0)eventValues["image"]=imageScriptValue;var descriptionScriptValue=populateDescriptionScript(parentDiv);if(descriptionScriptValue.length>
0)eventValues["description"]=descriptionScriptValue;console.log("json \x3d "+JSON.stringify(eventValues));return eventValues}
function populateLocationScript(parentDiv){var locationValues={};locationValues["@type"]="Place";$(".seo-location",parentDiv).each(function(i){$(this).each(function(){var schemaType=$(this).attr("data-seo-schema");if(schemaType=="Event"){var seo_element_val=$(this).text().trim();seo_element_val=seo_element_val.replace(/[\r\n]+/g," ");locationValues[$(this).attr("data-seo-element")]=seo_element_val}})});console.log("location json \x3d "+JSON.stringify(locationValues));return locationValues}
function populateOffersScript(parentDiv){var offers={};offers["@type"]="Offer";$(".seo-offers",parentDiv).each(function(i){$(this).each(function(){var schemaType=$(this).attr("data-seo-schema");if(schemaType=="Event"){var seo_element_val=$(this).text().trim();seo_element_val=seo_element_val.replace(/[\r\n]+/g," ");offers[$(this).attr("data-seo-element")]=seo_element_val}})});console.log("offers json \x3d "+JSON.stringify(offers));return offers}
function populateImageScript(parentDiv){var imageAttribute="";var nextSibling=$(parentDiv).next();var imageAttribute=$(".seo-event-image",nextSibling).first().text().trim();if(imageAttribute.length==0)var imageAttribute=$(parentDiv).parents(".eventdetailslistcontainer").siblings().find(".seo-event-image").text().trim();console.log("image attribute \x3d "+imageAttribute);return imageAttribute}
function populateDescriptionScript(parentDiv){var textAttribute="";var nextSibling=$(parentDiv).next();var textAttribute=$(".seo-event-text",nextSibling).first().text().trim();if(textAttribute.length==0)var textAttribute=$(parentDiv).parents(".eventdetailslistcontainer").siblings().find(".seo-event-text").text().trim();console.log("text attribute \x3d "+textAttribute);return textAttribute}
function populateNameScript(parentDiv){var nameAttribute="";nameAttribute=$(parentDiv).parents(".eventdetailslistcontainer").siblings().find(".seo-event-name").text().trim();console.log("name attribute \x3d "+nameAttribute);return nameAttribute};