function FormHelper(){this.isValidVisitor=true;this.errorCheck=function(noValidation,eventType){var errorCount=0;var inputEmptyFilter=function(){return $.trim(this.value).length===0&&$(this).is(":visible")&&$(this).attr("type")!="hidden"};$(".MainParsys form .form_row").each(function(){if($("form_leftcolmark",$(this)).text()=="*"&&$("input",$(this)).filter(inputEmptyFilter).length>0)errorCount++});if(errorCount===0&&noValidation=="false"||noValidation=="true"){if(eventType=="FormSubmit"){FormHelper.addHiddenMarketingData("hiddenFields");
FormHelper.addHiddenFormFields()}var cidFormField=$("input:hidden[id\x3dcid-tc]");if(typeof cidFormField!="undefined"&&cidFormField!=null&&typeof digitalData!="undefined")cidFormField.val(digitalData.merchandising.cid);var icidFormField=$("input:hidden[id\x3dicid-tc]");if(typeof icidFormField!="undefined"&&icidFormField!=null&&typeof digitalData!="undefined")icidFormField.val(digitalData.merchandising.icid);this.setEcidCookieValue();this.setAAMUUID();return false}};this.onSubmitConcatFields=function(){$(".field-concat-control").each(function(i,
e){var controlValues=[];var fields=$(this).attr("data-concat-fields").split(",");var $form=$(this).closest("form");for(var j=0;j<fields.length;j++){var $field=$("[name\x3d"+fields[j]+"]",$form);var fieldValue="";var fieldType=$field.attr("type");if(fieldType=="checkbox"||fieldType=="radio"){var chkArray=[];$.each($field,function(index,item){console.log(this);if($(this).is(":checked")||$(this).is(":selected"))chkArray.push($(this).val())});fieldValue=chkArray.join(";")}else if($field.is("select")){var $thisSelected=
$("option:selected",$field);if(!$thisSelected.attr("disabled"))fieldValue=fieldValue=$field.val()}else fieldValue=$field.val();fieldValue=$.trim(fieldValue);controlValues.push(fieldValue)}$(this).val(controlValues.join(","))})};this.addHiddenFormFields=function(){$.ajax({dataType:"json",url:"/bin/lifetech/token.json?cache\x3dfalse",async:false,success:function(response){var hiddenDiv=$("#preferredEmailContainer");if(hiddenDiv.length==0)return;var token=response.token;var hiddenField=$("#email_token");
if(hiddenField.length==0){var emailHiddenField='\x3cinput id\x3d"preferred_email_token" type\x3d"hidden" name\x3d"preferred_email_token" value\x3d"'+token+'"/\x3e';hiddenDiv.append(emailHiddenField)}else hiddenField.val(token)}})};this.sendToInteract=function(){console.log("form submit url \x3d "+window.location.pathname);var pagePath=window.location.pathname;var sessionId="";sessionId=digitalData.merchandising.sessionId!==null?digitalData.merchandising.sessionId:getCookie("s_vi");if(typeof Offers!==
"undefined"&&typeof Offers.postFormSubmitEventToInteractServlet=="function")Offers.postFormSubmitEventToInteractServlet(sessionId,pagePath);console.log("params \x3d "+sessionId+"-"+pagePath)};this.addHiddenTokenData=function(hiddenDiv){if(typeof digitalData!=="undefined"){var icidHiddenField='\x3cinput type\x3d"hidden" class\x3d"tracking_icid" name\x3d"icid" value\x3d"'+digitalData.merchandising.icid+'"'+"/\x3e";hiddenDiv.innerHTML+=icidHiddenField;var cidHiddenField='\x3cinput type\x3d"hidden" class\x3d"tracking_cid" name\x3d"cid" value\x3d"'+
digitalData.merchandising.cid+'"'+"/\x3e";hiddenDiv.innerHTML+=cidHiddenField;var sessionIdHiddenField='\x3cinput type\x3d"hidden" class\x3d"tracking_s_vi" name\x3d"s_vi" value\x3d"'+digitalData.merchandising.sessionId+'"'+"/\x3e";hiddenDiv.innerHTML+=sessionIdHiddenField;var s_vi_lowHiddenField='\x3cinput type\x3d"hidden" class\x3d"tracking_post_visid_low" name\x3d"post_visid_low" value\x3d"'+digitalData.merchandising.s_vi_low+'"'+"/\x3e";hiddenDiv.innerHTML+=s_vi_lowHiddenField;var s_vi_highHiddenField=
'\x3cinput type\x3d"hidden" class\x3d"tracking_post_visid_high" name\x3d"post_visid_high" value\x3d"'+digitalData.merchandising.s_vi_high+'"'+"/\x3e";hiddenDiv.innerHTML+=s_vi_highHiddenField;var referrerHiddenField='\x3cinput type\x3d"hidden" class\x3d"tracking_refer_domain_nm" name\x3d"refer_domain_nm" value\x3d"'+digitalData.merchandising.referrer+'"'+"/\x3e";hiddenDiv.innerHTML+=referrerHiddenField}return hiddenDiv};this.addHiddenFormFieldsComplete=false;this.addHiddenMarketingData=function(elementId){if(this.addHiddenFormFieldsComplete)return true;
this.addHiddenFormFieldsComplete=true;if(typeof elementId=="undefined")return true;if(!this.isValidVisitor)return;var hiddenDiv=document.getElementById("hiddenFields");if(typeof hiddenDiv==="undefined"||hiddenDiv===null)return;hiddenDiv.innerHTML="";hiddenDiv=this.addHiddenTokenData(hiddenDiv)};this.isValidVisitor=function(){if(digitalData.merchandising.sessionId==="cookies-disabled"||digitalData.merchandising.sessionId==="bot-detected")return false};this.setEcidCookieValue=function(){var ecidInput=
document.getElementById("ECID");var ecidCookie=getCookie("s_ecid");if(ecidInput&&ecidCookie)ecidInput.setAttribute("value",ecidCookie)};this.setAAMUUID=function(){var AAMUUIDInput=document.getElementById("AAMUUID");if(typeof digitalData!=="undefined"&&AAMUUIDInput){var AAMUUID=digitalData.merchandising.marketingCloudVisitorID;AAMUUIDInput.setAttribute("value",AAMUUID)}}}var FormHelper=new FormHelper;function errorCheck(noValidation,eventType){FormHelper.errorCheck(noValidation,eventType)}
function onSubmitConcatFields(){FormHelper.onSubmitConcatFields()}function sendToInteract(){FormHelper.sendToInteract()}function isValidVisitor(){FormHelper.isValidVisitor()};